import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"
import { PGlite } from "@electric-sql/pglite"

import { buildChoiceOnlySeatingPlan } from "./choice-only-seating.mjs"

const EVENT3_MATCH_ID = "00000000-0000-0000-0000-000000000003"
const STATIC_MATCH_ID = "00000000-0000-0000-0000-000000000000"
const ATTENDANCE_MATCH_ID = "00000000-0000-0000-0000-000000000000"
const EVENT_ID = 26
const PARTICIPANT_NUMBERS = Array.from({ length: 42 }, (_, index) => index + 1)

const FIRST_PAIRS = Array.from({ length: 21 }, (_, index) => [index * 2 + 1, index * 2 + 2])
const SECOND_PAIRS = [[42, 1], ...Array.from({ length: 20 }, (_, index) => [index * 2 + 2, index * 2 + 3])]
const THIRD_PAIRS = Array.from({ length: 21 }, (_, index) => [index + 1, index + 22])

const matchRows = pairs => pairs.flatMap(([a, b]) => [
  { participant_number: a, partner_number: b, score: 50 },
  { participant_number: b, partner_number: a, score: 50 },
])

const matchTables = pairs => pairs.flatMap(([a, b], index) => [
  { participant_id: a, table_number: index + 1 },
  { participant_id: b, table_number: index + 1 },
])

function seatingPayload() {
  const plan = buildChoiceOnlySeatingPlan(PARTICIPANT_NUMBERS, { genderMap: {}, ageMap: {} })
  assert.equal(plan.error, undefined)
  const participants = PARTICIPANT_NUMBERS.map(participantNumber => ({
    participant_number: participantNumber,
    position: plan.positionMap[participantNumber],
  }))
  const assignments = []
  for (const [roundIndex, groups] of [plan.round1, plan.round2, plan.round3].entries()) {
    for (const [tableIndex, group] of groups.entries()) {
      for (const participantId of group) {
        assignments.push({
          round: roundIndex + 1,
          table_number: tableIndex + 1,
          participant_id: participantId,
        })
      }
    }
  }
  return { plan, participants, assignments }
}

function rankingRowsForPairs(...pairRounds) {
  const targetsByRanker = new Map(PARTICIPANT_NUMBERS.map(number => [number, new Set()]))
  for (const pairs of pairRounds) {
    for (const [a, b] of pairs) {
      targetsByRanker.get(a).add(b)
      targetsByRanker.get(b).add(a)
    }
  }
  return [...targetsByRanker].flatMap(([rankerNumber, targets]) =>
    [...targets].sort((a, b) => a - b).map((rankedNumber, index) => ({
      ranker_number: rankerNumber,
      ranked_number: rankedNumber,
      rank: index + 1,
    })))
}

const sortedRankingSnapshot = rows => [...rows]
  .sort((left, right) => left.ranker_number - right.ranker_number
    || left.rank - right.rank
    || left.ranked_number - right.ranked_number)
  .map(row => [row.ranker_number, row.ranked_number, row.rank])

async function expectDbError(promise, pattern) {
  await assert.rejects(promise, error => {
    assert.match(String(error?.message || error), pattern)
    return true
  })
}

async function createFixture(t, { beforeVariableRuntime } = {}) {
  const db = new PGlite()
  t.after(() => db.close())
  await db.exec(`
    create role anon;
    create role authenticated;
    create role service_role;

    create table participants (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      assigned_number integer not null,
      updated_at timestamptz,
      survey_data_updated_at timestamptz,
      gender text,
      age integer,
      unique (match_id, assigned_number)
    );
    create table event_state (
      match_id uuid primary key,
      current_event_id integer,
      phase text,
      current_round integer,
      global_timer_active boolean,
      global_timer_start_time timestamptz,
      global_timer_duration integer,
      global_timer_round integer,
      phase2_score_revealed boolean,
      phase3_score_revealed boolean,
      groups_locked boolean default false,
      test_mode_active boolean default false,
      test_mode_snapshot jsonb
    );
    create table event3_participants (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      participant_number integer not null,
      position integer not null,
      phase2_excluded boolean default false,
      unique (match_id, event_id, participant_number),
      unique (match_id, event_id, position)
    );
    create table event3_matches (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      participant_number integer not null,
      phase2_partner integer,
      phase2_score integer,
      phase2_score_model_version text,
      phase2_score_snapshot jsonb,
      phase2_score_content_hash text,
      phase2_word text,
      phase2_feedback jsonb,
      phase3_partner integer,
      phase3_score integer,
      phase3_score_model_version text,
      phase3_score_snapshot jsonb,
      phase3_score_content_hash text,
      phase3_word text,
      phase3_feedback jsonb,
      match_preference text,
      updated_at timestamptz default now(),
      unique (match_id, event_id, participant_number)
    );
    create table session_assignments (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      round smallint not null,
      table_number integer not null,
      participant_id integer not null,
      unique (match_id, event_id, round, participant_id)
    );
    create table participant_rankings (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      ranker_number integer not null,
      ranked_number integer not null,
      rank integer not null,
      auto_saved boolean default false,
      unique (match_id, event_id, ranker_number, ranked_number),
      unique (match_id, event_id, ranker_number, rank)
    );
    create table event3_ranking_drafts (
      match_id uuid not null,
      event_id integer not null,
      ranker_number integer not null,
      completed_rounds smallint constraint event3_ranking_drafts_completed_rounds_check check (completed_rounds in (1, 2)),
      session_key text not null,
      ranked_numbers integer[] not null,
      revision bigint not null,
      submitted boolean default false,
      updated_at timestamptz default now(),
      primary key (match_id, event_id, ranker_number, completed_rounds, session_key)
    );
    create table event3_group_member_feedback (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      group_round smallint constraint event3_group_member_feedback_round check (group_round in (1, 2)),
      reviewer_number integer not null,
      member_number integer not null,
      experience text not null check (experience in ('great', 'good', 'neutral', 'uncomfortable')),
      tags text[] not null default '{}',
      organizer_note text,
      is_test_mode boolean not null default false,
      submitted_at timestamptz default now(),
      updated_at timestamptz default now(),
      unique (match_id, event_id, group_round, reviewer_number, member_number, is_test_mode)
    );
    create table event3_group_reflections (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      ranker_number integer not null,
      ranked_numbers integer[] not null default '{}',
      organizer_note text,
      source_phase text not null default 'ranking1'
        constraint event3_group_reflections_source_phase check (source_phase in ('ranking1', 'ranking2')),
      submitted_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      group_round integer not null default 1
        constraint event3_group_reflections_group_round check (group_round in (1, 2)),
      unique (match_id, event_id, ranker_number, group_round)
    );
    create table event3_exclusions (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      participant_a_number integer not null,
      participant_b_number integer not null,
      reason text,
      created_at timestamptz default now(),
      unique (match_id, event_id, participant_a_number, participant_b_number)
    );
    create table locked_matches (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      participant1_number integer not null,
      participant2_number integer not null
    );
    create table event_attendance (
      match_id uuid not null,
      event_id integer not null,
      participant_number integer not null,
      attended boolean not null default false,
      updated_at timestamptz default now(),
      updated_by text,
      primary key (match_id, event_id, participant_number)
    );
    create table organizer_requests (
      id uuid primary key default gen_random_uuid(),
      event_id integer,
      participant_token text not null,
      participant_number integer,
      participant_name text,
      table_info text,
      message text,
      organizer_reply text,
      status text default 'pending',
      request_type text default 'chat',
      chat_history jsonb default '[]'::jsonb,
      created_at timestamptz default now(),
      updated_at timestamptz default now()
    );

    create table event3_test_mode_snapshots (
      match_id uuid not null,
      event_id integer not null,
      snapshot jsonb not null,
      created_at timestamptz default now(),
      primary key (match_id, event_id)
    );
    create table event3_test_match_results (match_id uuid, event_id integer);
    create table event3_participant_notes (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      participant_number integer not null,
      about_number integer,
      phase integer,
      note text not null,
      created_at timestamptz default now()
    );
    create table event3_mood_checks (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      check_id text not null,
      participant_number integer not null,
      mood text,
      triggered_at timestamptz not null default now(),
      answered_at timestamptz,
      unique (match_id, check_id, participant_number)
    );
    create table event3_notifications (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      notif_id text not null,
      participant_number integer not null,
      title text not null,
      body text,
      icon text default 'info',
      created_at timestamptz not null default now(),
      seen_at timestamptz,
      unique (match_id, notif_id, participant_number)
    );
    create table event3_cohost_notes (
      id uuid primary key default gen_random_uuid(),
      match_id uuid not null,
      event_id integer not null,
      test_mode boolean not null default false,
      test_session_key text not null default '',
      scope_type text not null check (scope_type in ('event', 'table', 'participant', 'pair')),
      scope_key text not null,
      round smallint constraint event3_cohost_notes_round_check check (round in (1, 2, 3, 20, 30)),
      table_number integer,
      participant_number integer,
      participant2_number integer,
      note text not null,
      updated_by text not null default 'event3-cohost',
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      constraint event3_cohost_notes_scope_unique unique (
        match_id, event_id, test_mode, test_session_key, scope_key
      ),
      constraint event3_cohost_notes_scope_shape check (
        (scope_type = 'event' and round is null and table_number is null
          and participant_number is null and participant2_number is null)
        or (scope_type = 'table' and round is not null and table_number is not null
          and participant_number is null and participant2_number is null)
        or (scope_type = 'participant' and round is null and table_number is null
          and participant_number is not null and participant2_number is null)
        or (scope_type = 'pair' and round in (20, 30) and table_number is null
          and participant_number is not null and participant2_number is not null
          and participant_number < participant2_number)
      )
    );
    create table event3_ai_welcome_messages (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      participant_number integer not null,
      welcome_message text not null,
      generated_at timestamptz default now(),
      generated_by text default 'system',
      anchor_used text,
      unique (match_id, event_id, participant_number)
    );

    create function event3_expected_ranked_numbers(
      p_match_id uuid, p_event_id integer, p_ranker_number integer, p_completed_rounds integer
    ) returns integer[] language sql stable set search_path = public as $expected$
      select coalesce(array_agg(target order by first_round, target), '{}'::integer[])
      from (
        select tablemate.participant_id as target, min(ranker.round) as first_round
        from session_assignments ranker
        join session_assignments tablemate
          on tablemate.match_id = ranker.match_id
          and tablemate.event_id = ranker.event_id
          and tablemate.round = ranker.round
          and tablemate.table_number = ranker.table_number
          and tablemate.participant_id <> ranker.participant_id
        where ranker.match_id = p_match_id
          and ranker.event_id = p_event_id
          and ranker.participant_id = p_ranker_number
          and ranker.round between 1 and p_completed_rounds
        group by tablemate.participant_id
      ) peers
    $expected$;

    create function replace_event3_participant(
      uuid, uuid, integer, integer, integer, jsonb, jsonb
    ) returns jsonb language sql as $delegate$
      select jsonb_build_object('delegate', 'replace_event3_participant')
    $delegate$;
    create function swap_event3_match_partner(
      uuid, integer, text, integer, integer, integer, integer, jsonb, jsonb
    ) returns jsonb language sql as $delegate$
      select jsonb_build_object('delegate', 'swap_event3_match_partner')
    $delegate$;
    create function replace_event3_algorithm_match_partner(
      uuid, uuid, integer, integer, integer, integer, integer, jsonb, jsonb, boolean
    ) returns jsonb language sql as $delegate$
      select jsonb_build_object('delegate', 'replace_event3_algorithm_match_partner')
    $delegate$;

    create function replace_event3_group_member_feedback(
      uuid, integer, smallint, integer, boolean, jsonb
    ) returns integer language sql as $legacy$ select 0 $legacy$;
    create function end_event3_test_mode(p_event_id integer)
    returns jsonb language plpgsql as $legacy$
    declare
      v_snapshot jsonb;
    begin
      select snapshot into v_snapshot
      from public.event3_test_mode_snapshots
      where match_id = '${EVENT3_MATCH_ID}'::uuid and event_id = p_event_id;
      delete from public.event3_participant_notes
      where match_id = '${EVENT3_MATCH_ID}'::uuid and event_id = p_event_id;
      insert into public.event3_participant_notes
      select restored.* from jsonb_populate_recordset(
        null::public.event3_participant_notes,
        coalesce(v_snapshot -> 'event3_participant_notes', '[]'::jsonb)
      ) restored;
      delete from public.event3_mood_checks
      where match_id = '${EVENT3_MATCH_ID}'::uuid and event_id = p_event_id;
      insert into public.event3_mood_checks
      select restored.* from jsonb_populate_recordset(
        null::public.event3_mood_checks,
        coalesce(v_snapshot -> 'event3_mood_checks', '[]'::jsonb)
      ) restored;
      delete from public.event3_notifications
      where match_id = '${EVENT3_MATCH_ID}'::uuid and event_id = p_event_id;
      insert into public.event3_notifications
      select restored.* from jsonb_populate_recordset(
        null::public.event3_notifications,
        coalesce(v_snapshot -> 'event3_notifications', '[]'::jsonb)
      ) restored;
      delete from public.event3_ai_welcome_messages
      where match_id = '${EVENT3_MATCH_ID}'::uuid and event_id = p_event_id;
      insert into public.event3_ai_welcome_messages
      select restored.* from jsonb_populate_recordset(
        null::public.event3_ai_welcome_messages,
        coalesce(v_snapshot -> 'event3_ai_welcome_messages', '[]'::jsonb)
      ) restored;
      update public.event_state
      set test_mode_active = false, test_mode_snapshot = null
      where match_id = '${EVENT3_MATCH_ID}'::uuid and current_event_id = p_event_id;
      delete from public.event3_test_mode_snapshots
      where match_id = '${EVENT3_MATCH_ID}'::uuid and event_id = p_event_id;
      return jsonb_build_object('success', true, 'snapshot_version', 1);
    end;
    $legacy$;

    -- This trigger is installed by the ranking-draft migration that precedes
    -- the choice-only migration in production. Keeping it in the fixture
    -- catches live-draft mutations caused by test-mode transition ordering.
    create function invalidate_event3_ranking_draft()
    returns trigger language plpgsql as $trigger$
    declare
      v_match uuid;
      v_event integer;
      v_ranker integer;
      v_session text;
    begin
      if tg_op = 'DELETE' then
        v_match := old.match_id;
        v_event := old.event_id;
        v_ranker := old.ranker_number;
      else
        v_match := new.match_id;
        v_event := new.event_id;
        v_ranker := new.ranker_number;
      end if;
      select case when test_mode_active
        then coalesce(test_mode_snapshot ->> 'started_at', 'legacy-test')
        else 'live' end
      into v_session from public.event_state where match_id = v_match;
      update public.event3_ranking_drafts set submitted = true
        where match_id = v_match and event_id = v_event and ranker_number = v_ranker
          and session_key = v_session and not submitted;
      return null;
    end;
    $trigger$;
    create trigger event3_invalidate_draft_on_ballot_change
      after insert or update or delete on participant_rankings
      for each row execute function invalidate_event3_ranking_draft();
  `)

  const migration = await readFile(new URL(
    "../../supabase/migrations/20260901104855_add_event3_choice_only_three_groups.sql",
    import.meta.url,
  ), "utf8")
  await db.exec(migration)
  const previewMigration = await readFile(new URL(
    "../../supabase/migrations/20260902031039_event3_choice_seating_preview_reports.sql",
    import.meta.url,
  ), "utf8")
  await db.exec(previewMigration)
  const flexibleRosterMigration = await readFile(new URL(
    "../../supabase/migrations/20260905024500_allow_flexible_event3_choice_rosters.sql",
    import.meta.url,
  ), "utf8")
  await db.exec(flexibleRosterMigration)
  const supportMigration = await readFile(new URL(
    "../../supabase/migrations/20260830093718_event3_atomic_support_chat.sql",
    import.meta.url,
  ), "utf8")
  await db.exec(supportMigration)
  if (beforeVariableRuntime) await beforeVariableRuntime(db)
  const variableTestRuntimeMigration = await readFile(new URL(
    "../../supabase/migrations/20260905125242_harden_event3_variable_test_runtime.sql",
    import.meta.url,
  ), "utf8")
  await db.exec(variableTestRuntimeMigration)
  const sixPersonTablesMigration = await readFile(new URL(
    "../../supabase/migrations/20260905180000_event3_six_person_group_tables.sql",
    import.meta.url,
  ), "utf8")
  await db.exec(sixPersonTablesMigration)
  return db
}

test("choice-only migration hardens format, seating, matching, and feedback without partial writes", async t => {
  const db = await createFixture(t)
  const { plan, participants, assignments } = seatingPayload()

  const previewSecurity = await db.query(`select
    (select relrowsecurity from pg_class where oid='public.event3_choice_seating_reports'::regclass) as rls_enabled,
    has_table_privilege('anon','public.event3_choice_seating_reports','select') as anon_can_read,
    has_table_privilege('authenticated','public.event3_choice_seating_reports','insert') as authenticated_can_insert,
    has_table_privilege('service_role','public.event3_choice_seating_reports','select') as service_can_read,
    has_function_privilege('anon','public.touch_event3_choice_profile_version()','execute') as anon_can_touch_profile_version,
    has_function_privilege(
      'anon',
      'public.apply_event3_choice_seating_preview(uuid,uuid,integer,boolean,text,jsonb,jsonb,jsonb,jsonb,jsonb,bigint,jsonb,text,text,smallint,text,jsonb)',
      'execute'
    ) as anon_can_apply,
    has_function_privilege(
      'service_role',
      'public.apply_event3_choice_seating_preview(uuid,uuid,integer,boolean,text,jsonb,jsonb,jsonb,jsonb,jsonb,bigint,jsonb,text,text,smallint,text,jsonb)',
      'execute'
    ) as service_can_apply`)
  assert.deepEqual(previewSecurity.rows, [{
    rls_enabled: true,
    anon_can_read: false,
    authenticated_can_insert: false,
    service_can_read: true,
    anon_can_touch_profile_version: false,
    anon_can_apply: false,
    service_can_apply: true,
  }])

  await db.query(`insert into event_state(
    match_id,current_event_id,phase,current_round,test_mode_active,
    phase2_score_revealed,phase3_score_revealed
  ) values ($1,$2,'setup',1,false,false,false)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into participants(match_id,assigned_number)
    select $1, number from generate_series(1,42) number`, [STATIC_MATCH_ID])

  const legacyFeedback = await db.query(`select
    to_regprocedure('public.replace_event3_group_member_feedback(uuid,integer,smallint,integer,boolean,jsonb)')::text as signature,
    to_regprocedure('public.replace_event3_group_member_feedback_v2(uuid,integer,smallint,integer,boolean,text,jsonb)')::text as hardened_signature`)
  assert.equal(legacyFeedback.rows[0].signature, "replace_event3_group_member_feedback(uuid,integer,smallint,integer,boolean,jsonb)")
  assert.equal(legacyFeedback.rows[0].hardened_signature, "replace_event3_group_member_feedback_v2(uuid,integer,smallint,integer,boolean,text,jsonb)")

  await db.query("select set_event3_event_format($1,$2,'choice_only_three_groups')", [EVENT3_MATCH_ID, EVENT_ID])
  const formats = await db.query("select event_format from event3_event_settings")
  assert.deepEqual(formats.rows, [{ event_format: "choice_only_three_groups" }])

  await db.query(`insert into event3_cohost_notes(
    match_id,event_id,scope_type,scope_key,round,table_number,note
  ) values ($1,$2,'table','table:40:9',40,9,'third table note')`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into event3_cohost_notes(
    match_id,event_id,scope_type,scope_key,round,participant_number,participant2_number,note
  ) values ($1,$2,'pair','pair:40:1-22',40,1,22,'third pair note')`, [EVENT3_MATCH_ID, EVENT_ID])
  const round40Notes = await db.query(`select scope_type,round,table_number,participant_number,participant2_number
    from event3_cohost_notes order by scope_type`)
  assert.deepEqual(round40Notes.rows, [
    { scope_type: "pair", round: 40, table_number: null, participant_number: 1, participant2_number: 22 },
    { scope_type: "table", round: 40, table_number: 9, participant_number: null, participant2_number: null },
  ])
  await expectDbError(db.query(`insert into event3_cohost_notes(
    match_id,event_id,scope_type,scope_key,round,participant_number,participant2_number,note
  ) values ($1,$2,'pair','pair:3:1-22',3,1,22,'invalid pair round')`, [EVENT3_MATCH_ID, EVENT_ID]), /event3_cohost_notes_scope_shape/i)

  await db.query(`insert into participant_rankings(
    match_id,event_id,ranker_number,ranked_number,rank
  ) values ($1,$2,1,2,1)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into event3_ranking_drafts(
    match_id,event_id,ranker_number,completed_rounds,session_key,ranked_numbers,revision
  ) values ($1,$2,1,3,'live','{}',1)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into event3_group_member_feedback(
    match_id,event_id,group_round,reviewer_number,member_number,experience,tags,is_test_mode
  ) values ($1,$2,3,1,2,'good','{}',false)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into event3_group_reflections(
    match_id,event_id,ranker_number,ranked_numbers,source_phase,group_round
  ) values ($1,$2,1,'{}','ranking3',3)`, [EVENT3_MATCH_ID, EVENT_ID])

  const trigger = await db.query("select count(*)::int as count from pg_trigger where tgname='event3_complete_rankings_before_phase_exit'")
  assert.equal(trigger.rows[0].count, 1)

  await db.query("delete from event3_group_reflections where match_id=$1 and event_id=$2", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("select begin_event3_test_mode($1,$2::integer[])", [EVENT_ID, PARTICIPANT_NUMBERS])
  const testState = await db.query("select test_mode_snapshot->>'started_at' as started_at from event_state where match_id=$1", [EVENT3_MATCH_ID])
  const startedAt = testState.rows[0].started_at
  assert.ok(startedAt)
  const liveDraftAfterTestStart = await db.query(`select submitted,revision,ranked_numbers
    from event3_ranking_drafts where match_id=$1 and event_id=$2 and session_key='live'`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(liveDraftAfterTestStart.rows, [{ submitted: false, revision: 1, ranked_numbers: [] }])

  await expectDbError(db.query(
    "select replace_event3_choice_seating($1,$2,true,'stale-session',$3::jsonb,$4::jsonb)",
    [EVENT3_MATCH_ID, EVENT_ID, JSON.stringify(participants), JSON.stringify(assignments)],
  ), /live\/test session changed/i)
  await db.query(
    "select replace_event3_choice_seating($1,$2,true,$3,$4::jsonb,$5::jsonb)",
    [EVENT3_MATCH_ID, EVENT_ID, startedAt, JSON.stringify(participants), JSON.stringify(assignments)],
  )
  const isolatedLiveRows = await db.query(`select
    (select count(*)::int from event3_ranking_drafts where session_key='live') as drafts,
    (select count(*)::int from event3_group_member_feedback where is_test_mode=false) as feedback`)
  assert.deepEqual(isolatedLiveRows.rows, [{ drafts: 1, feedback: 1 }])

  const rankingsBeforeStaleCompletion = await db.query(`select count(*)::int as count
    from participant_rankings where match_id=$1 and event_id=$2`, [EVENT3_MATCH_ID, EVENT_ID])
  await expectDbError(db.query(
    "select complete_event3_rankings_v2($1,$2,3,true,'stale-test-session')",
    [EVENT3_MATCH_ID, EVENT_ID],
  ), /live\/test session changed/i)
  const rankingsAfterStaleCompletion = await db.query(`select count(*)::int as count
    from participant_rankings where match_id=$1 and event_id=$2`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(rankingsAfterStaleCompletion.rows, rankingsBeforeStaleCompletion.rows)

  await db.query(`insert into event3_ranking_drafts(
    match_id,event_id,ranker_number,completed_rounds,session_key,ranked_numbers,revision
  ) values ($1,$2,1,3,$3,'{}',1)`, [EVENT3_MATCH_ID, EVENT_ID, startedAt])
  await db.query("update event_state set phase='round1' where match_id=$1", [EVENT3_MATCH_ID])
  await db.query(
    "select reset_event3_runtime_v2($1,$2,true,$3)",
    [EVENT3_MATCH_ID, EVENT_ID, startedAt],
  )
  const resetIsolation = await db.query(`select
    (select submitted from event3_ranking_drafts where match_id=$1 and event_id=$2 and session_key='live') as live_submitted,
    (select count(*)::int from event3_ranking_drafts where match_id=$1 and event_id=$2 and session_key=$3) as test_drafts,
    (select count(*)::int from event3_group_member_feedback where match_id=$1 and event_id=$2 and is_test_mode=false) as live_feedback,
    (select count(*)::int from event3_participants where match_id=$1 and event_id=$2) as participants,
    (select count(*)::int from session_assignments where match_id=$1 and event_id=$2) as assignments,
    (select phase from event_state where match_id=$1) as phase`, [EVENT3_MATCH_ID, EVENT_ID, startedAt])
  assert.deepEqual(resetIsolation.rows, [{
    live_submitted: false,
    test_drafts: 0,
    live_feedback: 1,
    participants: 0,
    assignments: 0,
    phase: "setup",
  }])

  // Return this focused fixture to an empty live setup. Test isolation itself
  // was verified above; the production end-test RPC is owned by an older migration.
  await db.query("delete from session_assignments where match_id=$1 and event_id=$2", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("delete from event3_participants where match_id=$1 and event_id=$2", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("delete from event3_ranking_drafts where match_id=$1 and event_id=$2", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("delete from event3_group_member_feedback where match_id=$1 and event_id=$2", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("update event_state set phase='setup',test_mode_active=false,test_mode_snapshot=null where match_id=$1", [EVENT3_MATCH_ID])

  await db.query(
    "select replace_event3_choice_roster($1,$2,$3,false,null,$4::integer[])",
    [EVENT3_MATCH_ID, STATIC_MATCH_ID, EVENT_ID, PARTICIPANT_NUMBERS],
  )
  const invalidRoster = [...PARTICIPANT_NUMBERS.slice(0, 41), 4242]
  await expectDbError(db.query(
    "select replace_event3_choice_roster($1,$2,$3,false,null,$4::integer[])",
    [EVENT3_MATCH_ID, STATIC_MATCH_ID, EVENT_ID, invalidRoster],
  ), /current participant/i)
  const rosterAfterFailure = await db.query("select count(*)::int as count,max(participant_number)::int as maximum from event3_participants")
  assert.deepEqual(rosterAfterFailure.rows, [{ count: 42, maximum: 42 }])

  const seatingReport = {
    schema_version: "event3-choice-seating-report-v1",
    candidate: { id: "r2-0-1-2-3-4-5-0-r3-0-2-4-1-3-5-0", rank: 2 },
    rounds: [],
    repeats: {},
    decision_context: {
      selected: { candidate_id: "r2-0-1-2-3-4-5-0-r3-0-2-4-1-3-5-0", rank: 2 },
      alternatives_summary: [
        { candidate_id: "best", rank: 1 },
        { candidate_id: "r2-0-1-2-3-4-5-0-r3-0-2-4-1-3-5-0", rank: 2 },
        { candidate_id: "third", rank: 3 },
      ],
    },
  }
  const profileVersions = PARTICIPANT_NUMBERS.map(participantNumber => ({
    participant_number: participantNumber,
    updated_at: null,
    survey_data_updated_at: null,
    gender: null,
    age: null,
  }))
  const expectedRoster = PARTICIPANT_NUMBERS.map((participant_number, position) => ({ participant_number, position }))
  const desiredParticipants = structuredClone(participants)
  ;[desiredParticipants[0].position, desiredParticipants[1].position] = [
    desiredParticipants[1].position,
    desiredParticipants[0].position,
  ]
  const approvalSql = `select apply_event3_choice_seating_preview(
    $1,$2,$3,false,null,$4::jsonb,$5::jsonb,$6::jsonb,$7::jsonb,$8::jsonb,$9::bigint,$10::jsonb,$11,$12,$13::smallint,$14,$15::jsonb
  ) as result`
  const approvalParams = [
    EVENT3_MATCH_ID,
    STATIC_MATCH_ID,
    EVENT_ID,
    JSON.stringify(desiredParticipants),
    JSON.stringify(expectedRoster),
    JSON.stringify(profileVersions),
    JSON.stringify([]),
    JSON.stringify([]),
    null,
    JSON.stringify(assignments),
    "a".repeat(64),
    seatingReport.candidate.id,
    seatingReport.candidate.rank,
    "spark-depth-rhythm-v1",
    JSON.stringify(seatingReport),
  ]
  await db.query("update event3_participants set position=42 where match_id=$1 and event_id=$2 and participant_number=1", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("update event3_participants set position=0 where match_id=$1 and event_id=$2 and participant_number=2", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("update event3_participants set position=1 where match_id=$1 and event_id=$2 and participant_number=1", [EVENT3_MATCH_ID, EVENT_ID])
  await expectDbError(db.query(approvalSql, approvalParams), /roster order changed since this preview/i)
  const untouchedAfterRosterReorder = await db.query(`select
    (select count(*)::int from session_assignments where match_id=$1 and event_id=$2) as assignments,
    (select count(*)::int from event3_choice_seating_reports where match_id=$1 and event_id=$2) as reports`,
  [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(untouchedAfterRosterReorder.rows, [{ assignments: 0, reports: 0 }])
  await db.query("update event3_participants set position=42 where match_id=$1 and event_id=$2 and participant_number=1", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("update event3_participants set position=1 where match_id=$1 and event_id=$2 and participant_number=2", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("update event3_participants set position=0 where match_id=$1 and event_id=$2 and participant_number=1", [EVENT3_MATCH_ID, EVENT_ID])

  // Runtime gates are checked again after the transaction-level event lock,
  // not only by the API before issuing the approval RPC.
  await db.query("update event_state set global_timer_active=true where match_id=$1", [EVENT3_MATCH_ID])
  await expectDbError(db.query(approvalSql, approvalParams), /active unlocked setup event/i)
  await db.query("update event_state set global_timer_active=false,groups_locked=true where match_id=$1", [EVENT3_MATCH_ID])
  await expectDbError(db.query(approvalSql, approvalParams), /active unlocked setup event/i)
  await db.query("update event_state set groups_locked=false where match_id=$1", [EVENT3_MATCH_ID])
  const untouchedAfterRuntimeGateFailures = await db.query(`select
    (select count(*)::int from session_assignments where match_id=$1 and event_id=$2) as assignments,
    (select count(*)::int from event3_choice_seating_reports where match_id=$1 and event_id=$2) as reports`,
  [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(untouchedAfterRuntimeGateFailures.rows, [{ assignments: 0, reports: 0 }])

  // Model two admins pressing Approve from the same empty-baseline preview.
  // Exactly one serialized transaction may win the compare-and-swap.
  const concurrentApprovals = await Promise.allSettled([
    db.query(approvalSql, approvalParams),
    db.query(approvalSql, approvalParams),
  ])
  const fulfilledApprovals = concurrentApprovals.filter(result => result.status === "fulfilled")
  const rejectedApprovals = concurrentApprovals.filter(result => result.status === "rejected")
  assert.equal(fulfilledApprovals.length, 1, concurrentApprovals.map(result => result.status === "rejected"
    ? String(result.reason?.message || result.reason)
    : "fulfilled").join(" | "))
  assert.equal(rejectedApprovals.length, 1)
  assert.match(String(rejectedApprovals[0].reason?.message || rejectedApprovals[0].reason), /changed since this preview/i)
  const approved = fulfilledApprovals[0].value
  assert.equal(approved.rows[0].result.assignments, 126)
  assert.equal(approved.rows[0].result.candidate_rank, 2)
  assert.ok(Number(approved.rows[0].result.report_id) > 0)
  const rosterAfterDesiredReorder = await db.query(`select participant_number,position
    from event3_participants where match_id=$1 and event_id=$2 order by participant_number`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(rosterAfterDesiredReorder.rows, desiredParticipants
    .map(row => ({ ...row })).sort((left, right) => left.participant_number - right.participant_number))
  const persistedReport = await db.query(`select
    candidate_id,candidate_rank,generator_version,context_hash,
    report->>'schema_version' as schema_version,
    jsonb_array_length(assignments)::int as assignment_count
    from event3_choice_seating_reports`)
  assert.deepEqual(persistedReport.rows, [{
    candidate_id: seatingReport.candidate.id,
    candidate_rank: 2,
    generator_version: "spark-depth-rhythm-v1",
    context_hash: "a".repeat(64),
    schema_version: "event3-choice-seating-report-v1",
    assignment_count: 126,
  }])

  const reportCountAfterStaleApproval = await db.query("select count(*)::int as count from event3_choice_seating_reports")
  assert.deepEqual(reportCountAfterStaleApproval.rows, [{ count: 1 }])

  // Even when the chosen candidate is byte-for-byte identical to current
  // seating, persisting the decision advances the signed report revision.
  // Exactly one concurrent use of that no-op preview can therefore succeed,
  // and replaying it after the winner commits must fail.
  const noOpApprovalParams = [
    EVENT3_MATCH_ID,
    STATIC_MATCH_ID,
    EVENT_ID,
    JSON.stringify(desiredParticipants),
    JSON.stringify(desiredParticipants),
    JSON.stringify(profileVersions),
    JSON.stringify([]),
    JSON.stringify(assignments),
    approved.rows[0].result.report_id,
    JSON.stringify(assignments),
    "d".repeat(64),
    seatingReport.candidate.id,
    seatingReport.candidate.rank,
    "spark-depth-rhythm-v1",
    JSON.stringify(seatingReport),
  ]
  const concurrentNoOpApprovals = await Promise.allSettled([
    db.query(approvalSql, noOpApprovalParams),
    db.query(approvalSql, noOpApprovalParams),
  ])
  const fulfilledNoOpApprovals = concurrentNoOpApprovals.filter(result => result.status === "fulfilled")
  const rejectedNoOpApprovals = concurrentNoOpApprovals.filter(result => result.status === "rejected")
  assert.equal(fulfilledNoOpApprovals.length, 1, concurrentNoOpApprovals.map(result => result.status === "rejected"
    ? String(result.reason?.message || result.reason)
    : "fulfilled").join(" | "))
  assert.equal(rejectedNoOpApprovals.length, 1)
  assert.match(String(rejectedNoOpApprovals[0].reason?.message || rejectedNoOpApprovals[0].reason), /decision changed since this preview/i)
  await expectDbError(db.query(approvalSql, noOpApprovalParams), /decision changed since this preview/i)
  const latestReportId = fulfilledNoOpApprovals[0].value.rows[0].result.report_id
  const reportCountAfterNoOpReplay = await db.query("select count(*)::int as count from event3_choice_seating_reports")
  assert.deepEqual(reportCountAfterNoOpReplay.rows, [{ count: 2 }])

  const currentBaselineParams = [
    EVENT3_MATCH_ID,
    STATIC_MATCH_ID,
    EVENT_ID,
    JSON.stringify(desiredParticipants),
    JSON.stringify(desiredParticipants),
    JSON.stringify(profileVersions),
    JSON.stringify([]),
    JSON.stringify(assignments),
    latestReportId,
    JSON.stringify(assignments),
    "c".repeat(64),
    seatingReport.candidate.id,
    seatingReport.candidate.rank,
    "spark-depth-rhythm-v1",
    JSON.stringify(seatingReport),
  ]
  await db.query("update participants set updated_at='2026-09-02T03:00:00Z' where match_id=$1 and assigned_number=1", [STATIC_MATCH_ID])
  await expectDbError(db.query(approvalSql, currentBaselineParams), /profiles changed since this preview/i)
  const refreshedProfileRows = await db.query(`select
    assigned_number as participant_number,updated_at,survey_data_updated_at,gender,age::text as age
    from participants where match_id=$1 order by assigned_number`, [STATIC_MATCH_ID])
  const refreshedProfileVersions = refreshedProfileRows.rows.map(row => ({
    ...row,
    updated_at: row.updated_at instanceof Date ? row.updated_at.toISOString() : row.updated_at,
    survey_data_updated_at: row.survey_data_updated_at instanceof Date
      ? row.survey_data_updated_at.toISOString()
      : row.survey_data_updated_at,
  }))
  assert.ok(refreshedProfileVersions[0].updated_at)
  const refreshedBaselineParams = [...currentBaselineParams]
  refreshedBaselineParams[5] = JSON.stringify(refreshedProfileVersions)

  await db.query(`insert into locked_matches(
    match_id,event_id,participant1_number,participant2_number
  ) values ($1,$2,1,2)`, [STATIC_MATCH_ID, EVENT_ID])
  await expectDbError(db.query(approvalSql, refreshedBaselineParams), /protected pairs changed since this preview/i)
  await db.query("delete from locked_matches where match_id=$1 and event_id=$2", [STATIC_MATCH_ID, EVENT_ID])

  await db.query(`insert into event3_exclusions(
    match_id,event_id,participant_a_number,participant_b_number
  ) values ($1,$2,3,4)`, [EVENT3_MATCH_ID, EVENT_ID])
  await expectDbError(db.query(approvalSql, refreshedBaselineParams), /protected pairs changed since this preview/i)
  await db.query("delete from event3_exclusions where match_id=$1 and event_id=$2", [EVENT3_MATCH_ID, EVENT_ID])
  const reportCountAfterContextChanges = await db.query("select count(*)::int as count from event3_choice_seating_reports")
  assert.deepEqual(reportCountAfterContextChanges.rows, [{ count: 2 }])

  const invalidAssignments = structuredClone(assignments)
  invalidAssignments[0].participant_id = invalidAssignments[1].participant_id
  await expectDbError(db.query(
    `select apply_event3_choice_seating_preview(
      $1,$2,$3,false,null,$4::jsonb,$5::jsonb,$6::jsonb,$7::jsonb,$8::jsonb,$9::bigint,$10::jsonb,$11,$12,$13::smallint,$14,$15::jsonb
    )`,
    [
      EVENT3_MATCH_ID,
      STATIC_MATCH_ID,
      EVENT_ID,
      JSON.stringify(desiredParticipants),
      JSON.stringify(desiredParticipants),
      JSON.stringify(refreshedProfileVersions),
      JSON.stringify([]),
      JSON.stringify(assignments),
      latestReportId,
      JSON.stringify(invalidAssignments),
      "b".repeat(64),
      seatingReport.candidate.id,
      seatingReport.candidate.rank,
      "spark-depth-rhythm-v1",
      JSON.stringify(seatingReport),
    ],
  ), /complete roster in groups of at most six/i)
  const seatingAfterFailure = await db.query("select round,count(*)::int as count from session_assignments group by round order by round")
  assert.deepEqual(seatingAfterFailure.rows, [
    { round: 1, count: 42 },
    { round: 2, count: 42 },
    { round: 3, count: 42 },
  ])
  const reportCountAfterFailure = await db.query("select count(*)::int as count from event3_choice_seating_reports")
  assert.deepEqual(reportCountAfterFailure.rows, [{ count: 2 }])

  const reviewer = 1
  const reviewerGroup = plan.round1.find(group => group.includes(reviewer))
  const tablemate = reviewerGroup.find(number => number !== reviewer)
  const outsider = PARTICIPANT_NUMBERS.find(number => !reviewerGroup.includes(number))
  const feedbackRows = [{ member_number: tablemate, experience: "good", tags: ["respectful"] }]
  await db.query(
    "select replace_event3_group_member_feedback_v2($1,$2,1::smallint,$3,false,null,$4::jsonb)",
    [EVENT3_MATCH_ID, EVENT_ID, reviewer, JSON.stringify(feedbackRows)],
  )
  await expectDbError(db.query(
    "select replace_event3_group_member_feedback_v2($1,$2,1::smallint,$3,false,null,$4::jsonb)",
    [EVENT3_MATCH_ID, EVENT_ID, reviewer, JSON.stringify([{ member_number: outsider, experience: "good" }])],
  ), /current tablemate/i)
  await expectDbError(db.query(
    "select replace_event3_group_member_feedback_v2($1,$2,1::smallint,$3,true,'wrong-mode',$4::jsonb)",
    [EVENT3_MATCH_ID, EVENT_ID, reviewer, JSON.stringify(feedbackRows)],
  ), /live\/test session changed/i)
  await db.query("update event_state set test_mode_active=true,test_mode_snapshot=jsonb_build_object('started_at','current-test-session') where match_id=$1", [EVENT3_MATCH_ID])
  await expectDbError(db.query(
    "select replace_event3_group_member_feedback_v2($1,$2,1::smallint,$3,true,'stale-test-session',$4::jsonb)",
    [EVENT3_MATCH_ID, EVENT_ID, reviewer, JSON.stringify(feedbackRows)],
  ), /live\/test session changed/i)
  await db.query(
    "select replace_event3_group_member_feedback_v2($1,$2,1::smallint,$3,true,'current-test-session',$4::jsonb)",
    [EVENT3_MATCH_ID, EVENT_ID, reviewer, JSON.stringify(feedbackRows)],
  )
  await db.query("update event_state set test_mode_active=false,test_mode_snapshot=null where match_id=$1", [EVENT3_MATCH_ID])

  await db.query("update event_state set phase='ranking3' where match_id=$1", [EVENT3_MATCH_ID])
  const rankerOneExpected = [...new Set([plan.round1, plan.round2, plan.round3]
    .flatMap(groups => groups.find(group => group.includes(1)))
    .filter(number => number !== 1))]
  await db.query(`insert into event3_ranking_drafts(
    match_id,event_id,ranker_number,completed_rounds,session_key,ranked_numbers,revision,submitted
  ) values ($1,$2,1,3,'live',$3::integer[],7,false)`, [
    EVENT3_MATCH_ID,
    EVENT_ID,
    rankerOneExpected,
  ])
  await db.query(
    "select replace_event3_choice_admin_rankings($1,$2,false,null,$3::integer[],'[]'::jsonb)",
    [EVENT3_MATCH_ID, EVENT_ID, [1]],
  )
  const clearedBallotState = await db.query(`select
    (select submitted from event3_ranking_drafts
      where match_id=$1 and event_id=$2 and ranker_number=1 and completed_rounds=3 and session_key='live') as submitted,
    (select count(*)::int from participant_rankings
      where match_id=$1 and event_id=$2 and ranker_number=1) as ranking_count`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(clearedBallotState.rows, [{ submitted: true, ranking_count: 0 }])
  await db.query("update event_state set phase='setup' where match_id=$1", [EVENT3_MATCH_ID])
  const clearedBallotAfterPhaseExit = await db.query(`select count(*)::int as count
    from participant_rankings where match_id=$1 and event_id=$2 and ranker_number=1`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(clearedBallotAfterPhaseExit.rows, [{ count: 0 }])

  const rankingRows = rankingRowsForPairs(FIRST_PAIRS, SECOND_PAIRS, THIRD_PAIRS)
  await db.query(`insert into participant_rankings(match_id,event_id,ranker_number,ranked_number,rank)
    select $1,$2,row_data.ranker_number,row_data.ranked_number,row_data.rank
    from jsonb_to_recordset($3::jsonb) row_data(ranker_number integer,ranked_number integer,rank integer)`,
  [EVENT3_MATCH_ID, EVENT_ID, JSON.stringify(rankingRows)])
  await db.query("update event_state set phase='phase2_processing' where match_id=$1", [EVENT3_MATCH_ID])

  const callMatch = (slot, pairs, expectedRankings, expectedExclusions = [], expectedTestMode = false, expectedStartedAt = null) => db.query(
    "select replace_event3_choice_match_round($1,$2,$3::smallint,$4,$5,$6::jsonb,$7::jsonb,$8::jsonb,$9::jsonb)",
    [
      EVENT3_MATCH_ID,
      EVENT_ID,
      slot,
      expectedTestMode,
      expectedStartedAt,
      JSON.stringify(expectedRankings),
      JSON.stringify(expectedExclusions),
      JSON.stringify(matchRows(pairs)),
      JSON.stringify(matchTables(pairs)),
    ],
  )
  const callInteraction = ({
    participantNumber,
    slot,
    partner,
    operation,
    payload,
    expectedTestMode = false,
    expectedStartedAt = null,
  }) => db.query(
    "select save_event3_match_interaction_v2($1,$2,$3,$4::smallint,$5,$6,$7,$8,$9::jsonb) as result",
    [
      EVENT3_MATCH_ID,
      EVENT_ID,
      participantNumber,
      slot,
      partner,
      expectedTestMode,
      expectedStartedAt,
      operation,
      JSON.stringify(payload),
    ],
  )
  let rankingSnapshot = sortedRankingSnapshot(rankingRows)

  await expectDbError(callMatch(1, FIRST_PAIRS, rankingSnapshot, [], true, "stale-session"), /live\/test session changed/i)
  await expectDbError(callMatch(1, FIRST_PAIRS, rankingSnapshot.slice(1)), /rankings changed/i)
  await expectDbError(callMatch(1, FIRST_PAIRS, rankingSnapshot, [[1, 2]]), /exclusions changed/i)

  await db.query(`insert into event3_exclusions(
    match_id,event_id,participant_a_number,participant_b_number,reason
  ) values ($1,$2,1,2,'test exclusion')`, [EVENT3_MATCH_ID, EVENT_ID])
  await expectDbError(callMatch(1, FIRST_PAIRS, rankingSnapshot, [[1, 2]]), /conflicts with a current event exclusion/i)
  await db.query("delete from event3_exclusions where match_id=$1 and event_id=$2", [EVENT3_MATCH_ID, EVENT_ID])

  const removedRanking = rankingRows.find(row => row.ranker_number === 2 && row.ranked_number === 1)
  await db.query("delete from participant_rankings where match_id=$1 and event_id=$2 and ranker_number=2 and ranked_number=1", [EVENT3_MATCH_ID, EVENT_ID])
  rankingSnapshot = sortedRankingSnapshot(rankingRows.filter(row => row !== removedRanking))
  await expectDbError(callMatch(1, FIRST_PAIRS, rankingSnapshot), /reciprocal in the persisted rankings/i)
  await db.query(`insert into participant_rankings(match_id,event_id,ranker_number,ranked_number,rank)
    values ($1,$2,$3,$4,$5)`, [EVENT3_MATCH_ID, EVENT_ID, removedRanking.ranker_number, removedRanking.ranked_number, removedRanking.rank])
  rankingSnapshot = sortedRankingSnapshot(rankingRows)

  const untouchedAfterFailures = await db.query(`select
    (select count(*)::int from event3_matches where phase2_partner is not null) as matches,
    (select count(*)::int from session_assignments where round=20) as tables`)
  assert.deepEqual(untouchedAfterFailures.rows, [{ matches: 0, tables: 0 }])

  await callMatch(1, FIRST_PAIRS, rankingSnapshot)
  await db.query("update event_state set phase='phase2_reveal' where match_id=$1", [EVENT3_MATCH_ID])

  await expectDbError(callInteraction({
    participantNumber: 1,
    slot: 1,
    partner: 2,
    operation: "feedback",
    payload: { rating: "stale" },
    expectedTestMode: true,
    expectedStartedAt: "stale-test-session",
  }), /live\/test session changed/i)
  await expectDbError(callInteraction({
    participantNumber: 1,
    slot: 1,
    partner: 3,
    operation: "feedback",
    payload: { rating: "wrong-partner" },
  }), /displayed Event3 partner changed/i)
  const firstFeedback = await callInteraction({
    participantNumber: 1,
    slot: 1,
    partner: 2,
    operation: "feedback",
    payload: { rating: "first-write" },
  })
  assert.equal(firstFeedback.rows[0].result.already_saved, false)
  const repeatedFeedback = await callInteraction({
    participantNumber: 1,
    slot: 1,
    partner: 2,
    operation: "feedback",
    payload: { rating: "must-not-overwrite" },
  })
  assert.equal(repeatedFeedback.rows[0].result.already_saved, true)
  const persistedFirstFeedback = await db.query(`select phase2_feedback
    from event3_matches where match_id=$1 and event_id=$2 and participant_number=1`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(persistedFirstFeedback.rows, [{ phase2_feedback: { rating: "first-write" } }])

  await db.query("update event3_matches set phase2_partner=3 where match_id=$1 and event_id=$2 and participant_number=2", [EVENT3_MATCH_ID, EVENT_ID])
  await expectDbError(callMatch(2, SECOND_PAIRS, rankingSnapshot), /complete reciprocal roster matching/i)
  const noSecondRoundAfterCorruption = await db.query(`select
    count(*) filter (where phase3_partner is not null)::int as matches,
    (select count(*)::int from session_assignments where round=30) as tables
    from event3_matches`)
  assert.deepEqual(noSecondRoundAfterCorruption.rows, [{ matches: 0, tables: 0 }])
  await db.query("update event3_matches set phase2_partner=1 where match_id=$1 and event_id=$2 and participant_number=2", [EVENT3_MATCH_ID, EVENT_ID])

  await callMatch(2, SECOND_PAIRS, rankingSnapshot)
  const firstTwoSaved = await db.query(`select
    count(*)::int as count,
    count(*) filter (where phase2_partner=phase3_partner)::int as repeats,
    count(*) filter (where phase2_partner is null or phase3_partner is null)::int as incomplete
    from event3_matches`)
  assert.deepEqual(firstTwoSaved.rows, [{ count: 42, repeats: 0, incomplete: 0 }])

  await db.query("update event_state set phase='phase2_processing' where match_id=$1", [EVENT3_MATCH_ID])
  await expectDbError(callMatch(1, FIRST_PAIRS, rankingSnapshot), /after the second match exists/i)

  await db.query("update event_state set phase='phase3_reveal' where match_id=$1", [EVENT3_MATCH_ID])
  const secondWord = await callInteraction({
    participantNumber: 1,
    slot: 2,
    partner: 42,
    operation: "word",
    payload: { word: "رائع" },
  })
  assert.equal(secondWord.rows[0].result.already_saved, false)
  const secondFeedback = await callInteraction({
    participantNumber: 1,
    slot: 2,
    partner: 42,
    operation: "feedback",
    payload: { rating: "second-match" },
  })
  assert.equal(secondFeedback.rows[0].result.already_saved, false)

  await db.query("update event3_matches set phase3_partner=2 where match_id=$1 and event_id=$2 and participant_number=42", [EVENT3_MATCH_ID, EVENT_ID])
  await expectDbError(callMatch(3, THIRD_PAIRS, rankingSnapshot), /complete reciprocal roster matchings/i)
  const noThirdRoundAfterCorruption = await db.query(`select
    count(*) filter (where phase4_partner is not null)::int as matches,
    (select count(*)::int from session_assignments where round=40) as tables
    from event3_matches`)
  assert.deepEqual(noThirdRoundAfterCorruption.rows, [{ matches: 0, tables: 0 }])
  await db.query("update event3_matches set phase3_partner=1 where match_id=$1 and event_id=$2 and participant_number=42", [EVENT3_MATCH_ID, EVENT_ID])

  await expectDbError(callMatch(3, FIRST_PAIRS, rankingSnapshot), /differ from both earlier choices/i)
  await expectDbError(callMatch(3, SECOND_PAIRS, rankingSnapshot), /differ from both earlier choices/i)
  await callMatch(3, THIRD_PAIRS, rankingSnapshot)
  const allThreeSaved = await db.query(`select
    count(*)::int as count,
    count(*) filter (where phase2_partner=phase3_partner
      or phase2_partner=phase4_partner or phase3_partner=phase4_partner)::int as repeats,
    count(*) filter (where phase2_partner is null or phase3_partner is null or phase4_partner is null)::int as incomplete,
    count(*) filter (where phase4_score=50)::int as scored
    from event3_matches`)
  assert.deepEqual(allThreeSaved.rows, [{ count: 42, repeats: 0, incomplete: 0, scored: 42 }])
  const oneToOneAssignments = await db.query("select round,count(*)::int as count from session_assignments where round in (20,30,40) group by round order by round")
  assert.deepEqual(oneToOneAssignments.rows, [
    { round: 20, count: 42 },
    { round: 30, count: 42 },
    { round: 40, count: 42 },
  ])
  const swappedRound40 = await db.query(`select swap_event3_table_numbers(
    $1,$2,array[40]::smallint[],1,2
  ) as result`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.equal(swappedRound40.rows[0].result.updated_assignments, 4)
  await db.query(`select swap_event3_table_numbers(
    $1,$2,array[40]::smallint[],1,2
  )`, [EVENT3_MATCH_ID, EVENT_ID])

  await db.query("update event_state set phase='phase2_reveal' where match_id=$1", [EVENT3_MATCH_ID])
  await expectDbError(callMatch(2, SECOND_PAIRS, rankingSnapshot), /after the third match exists/i)

  await db.query("update event_state set phase='phase4_reveal' where match_id=$1", [EVENT3_MATCH_ID])
  await expectDbError(callInteraction({
    participantNumber: 1,
    slot: 3,
    partner: 22,
    operation: "feedback",
    payload: { rating: "stale-third" },
    expectedTestMode: true,
    expectedStartedAt: "stale-test-session",
  }), /live\/test session changed/i)
  await expectDbError(callInteraction({
    participantNumber: 1,
    slot: 3,
    partner: 23,
    operation: "feedback",
    payload: { rating: "wrong-third-partner" },
  }), /displayed Event3 partner changed/i)
  const thirdWord = await callInteraction({
    participantNumber: 1,
    slot: 3,
    partner: 22,
    operation: "word",
    payload: { word: "ممتاز" },
  })
  assert.equal(thirdWord.rows[0].result.already_saved, false)
  const thirdFeedback = await callInteraction({
    participantNumber: 1,
    slot: 3,
    partner: 22,
    operation: "feedback",
    payload: { rating: "third-match" },
  })
  assert.equal(thirdFeedback.rows[0].result.already_saved, false)
  const repeatedThirdFeedback = await callInteraction({
    participantNumber: 1,
    slot: 3,
    partner: 22,
    operation: "feedback",
    payload: { rating: "must-not-overwrite-third" },
  })
  assert.equal(repeatedThirdFeedback.rows[0].result.already_saved, true)

  await db.query("update event_state set phase='final_reveal' where match_id=$1", [EVENT3_MATCH_ID])
  await db.query("update event3_event_settings set event_format='classic' where match_id=$1 and event_id=$2", [EVENT3_MATCH_ID, EVENT_ID])
  const classicPreference = await callInteraction({
    participantNumber: 1,
    slot: 2,
    partner: 42,
    operation: "preference",
    payload: { preference: "both" },
  })
  assert.equal(classicPreference.rows[0].result.already_saved, false)
  await expectDbError(callInteraction({
    participantNumber: 1,
    slot: 2,
    partner: 42,
    operation: "preference",
    payload: { preference: "third" },
  }), /invalid match preference/i)
  await db.query("update event3_event_settings set event_format='choice_only_three_groups' where match_id=$1 and event_id=$2", [EVENT3_MATCH_ID, EVENT_ID])
  await expectDbError(callInteraction({
    participantNumber: 1,
    slot: 2,
    partner: 42,
    operation: "preference",
    payload: { preference: "multiple" },
  }), /final match slot/i)
  await expectDbError(callInteraction({
    participantNumber: 1,
    slot: 3,
    partner: 22,
    operation: "preference",
    payload: { preference: "both" },
  }), /invalid match preference/i)
  const finalPreference = await callInteraction({
    participantNumber: 1,
    slot: 3,
    partner: 22,
    operation: "preference",
    payload: { preference: "multiple" },
  })
  assert.equal(finalPreference.rows[0].result.already_saved, false)
  const savedInteractions = await db.query(`select
    phase2_feedback,phase3_word,phase3_feedback,phase4_word,phase4_feedback,match_preference
    from event3_matches where match_id=$1 and event_id=$2 and participant_number=1`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(savedInteractions.rows, [{
    phase2_feedback: { rating: "first-write" },
    phase3_word: "رائع",
    phase3_feedback: { rating: "second-match" },
    phase4_word: "ممتاز",
    phase4_feedback: { rating: "third-match" },
    match_preference: "multiple",
  }])

  await db.query("update event_state set phase='setup' where match_id=$1", [EVENT3_MATCH_ID])
  await expectDbError(
    db.query("select set_event3_event_format($1,$2,'classic')", [EVENT3_MATCH_ID, EVENT_ID]),
    /clear this event/i,
  )
  const formatAfterRejectedSwitch = await db.query("select event_format from event3_event_settings where match_id=$1 and event_id=$2", [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(formatAfterRejectedSwitch.rows, [{ event_format: "choice_only_three_groups" }])
})

test("flexible choice migration saves and matches a 30-person live roster", async t => {
  const db = await createFixture(t)
  const roster = Array.from({ length: 30 }, (_, index) => index + 1)
  const plan = buildChoiceOnlySeatingPlan(roster, { genderMap: {}, ageMap: {} })
  assert.equal(plan.error, undefined)
  const participants = roster.map(participantNumber => ({
    participant_number: participantNumber,
    position: plan.positionMap[participantNumber],
  }))
  const expectedRoster = roster.map((participantNumber, position) => ({
    participant_number: participantNumber,
    position,
  }))
  const assignments = [plan.round1, plan.round2, plan.round3].flatMap((groups, roundIndex) =>
    groups.flatMap((group, tableIndex) => group.map(participantId => ({
      round: roundIndex + 1,
      table_number: tableIndex + 1,
      participant_id: participantId,
    }))))

  await db.query(`insert into event_state(
    match_id,current_event_id,phase,current_round,test_mode_active,
    phase2_score_revealed,phase3_score_revealed
  ) values ($1,$2,'setup',1,false,false,false)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into participants(match_id,assigned_number)
    select $1, number from generate_series(1,30) number`, [STATIC_MATCH_ID])
  await db.query("select set_event3_event_format($1,$2,'choice_only_three_groups')", [EVENT3_MATCH_ID, EVENT_ID])
  const rosterResult = await db.query(
    "select replace_event3_choice_roster($1,$2,$3,false,null,$4::integer[]) as result",
    [EVENT3_MATCH_ID, STATIC_MATCH_ID, EVENT_ID, roster],
  )
  assert.equal(rosterResult.rows[0].result.selected_count, 30)

  const profileVersions = roster.map(participantNumber => ({
    participant_number: participantNumber,
    updated_at: null,
    survey_data_updated_at: null,
    gender: null,
    age: null,
  }))
  const report = {
    schema_version: "event3-choice-seating-report-v1",
    candidate: { id: "flex-30-test", rank: 1 },
    decision_context: { alternatives_summary: [{ rank: 1 }, { rank: 2 }, { rank: 3 }] },
  }
  const approval = await db.query(`select apply_event3_choice_seating_preview(
    $1,$2,$3,false,null,$4::jsonb,$5::jsonb,$6::jsonb,$7::jsonb,$8::jsonb,null,$9::jsonb,$10,$11,$12::smallint,$13,$14::jsonb
  ) as result`, [
    EVENT3_MATCH_ID,
    STATIC_MATCH_ID,
    EVENT_ID,
    JSON.stringify(participants),
    JSON.stringify(expectedRoster),
    JSON.stringify(profileVersions),
    JSON.stringify([]),
    JSON.stringify([]),
    JSON.stringify(assignments),
    "a".repeat(64),
    "flex-30-test",
    1,
    "spark-depth-rhythm-v1-flexible",
    JSON.stringify(report),
  ])
  assert.equal(approval.rows[0].result.participants, 30)
  assert.equal(approval.rows[0].result.assignments, 90)

  const pairs = Array.from({ length: 15 }, (_, index) => [index * 2 + 1, index * 2 + 2])
  const rankings = pairs.flatMap(([a, b]) => [[a, b, 1], [b, a, 1]])
    .sort((left, right) => left[0] - right[0] || left[2] - right[2] || left[1] - right[1])
  await db.query(`insert into participant_rankings(match_id,event_id,ranker_number,ranked_number,rank)
    select $1,$2,row_data.ranker_number,row_data.ranked_number,row_data.rank
    from jsonb_to_recordset($3::jsonb) as row_data(ranker_number integer,ranked_number integer,rank integer)`, [
    EVENT3_MATCH_ID,
    EVENT_ID,
    JSON.stringify(rankings.map(([ranker_number, ranked_number, rank]) => ({ ranker_number, ranked_number, rank }))),
  ])
  await db.query("update event_state set phase='phase2_processing' where match_id=$1", [EVENT3_MATCH_ID])
  const matchResult = await db.query(`select replace_event3_choice_match_round(
    $1,$2,1::smallint,false,null,$3::jsonb,$4::jsonb,$5::jsonb,$6::jsonb
  ) as result`, [
    EVENT3_MATCH_ID,
    EVENT_ID,
    JSON.stringify(rankings),
    JSON.stringify([]),
    JSON.stringify(matchRows(pairs)),
    JSON.stringify(matchTables(pairs)),
  ])
  assert.equal(matchResult.rows[0].result.pairs, 15)
  const saved = await db.query(`select
    (select count(*)::int from event3_matches where match_id=$1 and event_id=$2) as matches,
    (select count(*)::int from session_assignments where match_id=$1 and event_id=$2 and round=20) as seats,
    (select count(*)::int from event3_choice_seating_reports where match_id=$1 and event_id=$2) as reports`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(saved.rows, [{ matches: 30, seats: 30, reports: 1 }])
})

test("choice test mode accepts 16, 30, and 42 participants and restores auxiliary live data", async t => {
  const db = await createFixture(t)
  await db.query(`insert into event_state(
    match_id,current_event_id,phase,current_round,test_mode_active,
    phase2_score_revealed,phase3_score_revealed
  ) values ($1,$2,'setup',1,false,false,false)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("select set_event3_event_format($1,$2,'choice_only_three_groups')", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into event_attendance(match_id,event_id,participant_number,attended,updated_by)
    values ($1,$2,101,true,'live-host')`, [ATTENDANCE_MATCH_ID, EVENT_ID])
  await db.query(`insert into organizer_requests(id,event_id,participant_token,participant_number,message)
    values ('00000000-0000-0000-0000-000000000101',$1,'live-token',101,'live request')`, [EVENT_ID])
  await db.query(`insert into organizer_requests(id,event_id,participant_token,participant_number,message)
    values ('00000000-0000-0000-0000-000000000102',null,'legacy-null-token',102,'legacy null request')`)
  await db.query(`insert into event3_group_reflections(
    match_id,event_id,ranker_number,ranked_numbers,source_phase,group_round
  ) values ($1,$2,101,'{102}','ranking1',1)`, [EVENT3_MATCH_ID, EVENT_ID])

  await expectDbError(
    db.query("select begin_event3_test_mode($1,$2::integer[])", [EVENT_ID, Array.from({ length: 15 }, (_, index) => index + 1)]),
    /even 16 to 42/i,
  )

  for (const count of [30, 16, 42]) {
    const selected = Array.from({ length: count }, (_, index) => index + 1)
    const begin = await db.query("select begin_event3_test_mode($1,$2::integer[]) as result", [EVENT_ID, selected])
    assert.equal(begin.rows[0].result.selected_count, count)
    const isolated = await db.query(`select
      (select count(*)::int from event_attendance where event_id=$1) as attendance,
      (select count(*)::int from organizer_requests where event_id=$1) as requests,
      (select count(*)::int from organizer_requests where event_id is null) as null_event_requests,
      (select count(*)::int from event3_group_reflections where event_id=$1) as reflections`, [EVENT_ID])
    assert.deepEqual(isolated.rows, [{ attendance: 0, requests: 0, null_event_requests: 1, reflections: 0 }])

    const session = await db.query("select test_mode_snapshot->>'started_at' as started_at from event_state where match_id=$1", [EVENT3_MATCH_ID])
    const startedAt = session.rows[0].started_at
    assert.ok(startedAt)
    if (count === 30) {
      await expectDbError(
        db.query(`select set_event3_attendance_v2(
          $1,1,true,null,false,true,$2
        )`, [EVENT_ID, startedAt]),
        /invalid Event3 attendance update/i,
      )
      await expectDbError(
        db.query(`select send_event3_support_message_v2(
          $1,1,'test-token','Test participant','table 1','request','chat',null,true,$2
        )`, [EVENT_ID, startedAt]),
        /invalid Event3 support request/i,
      )
    }
    const attendance = await db.query(`select set_event3_attendance_v2(
      $1,1,false,'event3-cohost',false,true,$2
    ) as result`, [EVENT_ID, startedAt])
    assert.deepEqual(attendance.rows[0].result, {
      success: true,
      participant_number: 1,
      attended: false,
      changed: true,
    })
    const support = await db.query(`select send_event3_support_message_v2(
      $1,1,'test-token','Test participant','table 1','test request','chat','user',true,$2
    ) as result`, [EVENT_ID, startedAt])
    const supportId = support.rows[0].result.id
    await db.query(`select append_event3_support_message_v2(
      $1,$2,'organizer reply','cohost',null,null,true,$3
    )`, [supportId, EVENT_ID, startedAt])
    await db.query(`select set_event3_support_status_v2(
      $1,$2,'resolved',false,true,$3
    )`, [EVENT_ID, supportId, startedAt])
    if (count === 30) {
      await expectDbError(
        db.query(`select set_event3_support_status_v2(
          $1,$2,null,false,true,$3
        )`, [EVENT_ID, supportId, startedAt]),
        /invalid Event3 support status update/i,
      )
    }
    await expectDbError(
      db.query(`select set_event3_attendance_v2(
        $1,1,true,'auto-join',true,true,'stale-test-session'
      )`, [EVENT_ID]),
      /live\/test session changed/i,
    )
    await expectDbError(
      db.query(`select send_event3_support_message_v2(
        $1,1,'test-token','Test participant','table 1','late request','chat','user',true,'stale-test-session'
      )`, [EVENT_ID]),
      /live\/test session changed/i,
    )
    await expectDbError(
      db.query(`select append_event3_support_message_v2(
        $1,$2,'late reply','cohost',null,null,true,'stale-test-session'
      )`, [supportId, EVENT_ID]),
      /live\/test session changed/i,
    )
    await expectDbError(
      db.query(`select set_event3_support_status_v2(
        $1,$2,'seen',false,true,'stale-test-session'
      )`, [EVENT_ID, supportId]),
      /live\/test session changed/i,
    )
    await expectDbError(
      db.query("select reset_event3_support_requests_v2($1,true,'stale-test-session')", [EVENT_ID]),
      /live\/test session changed/i,
    )
    await db.query(`insert into event3_cohost_notes(
      match_id,event_id,test_mode,test_session_key,scope_type,scope_key,note
    ) values ($1,$2,true,$3,'event','event','temporary cohost note')`, [EVENT3_MATCH_ID, EVENT_ID, startedAt])
    await db.query(`insert into event3_ranking_drafts(
      match_id,event_id,ranker_number,completed_rounds,session_key,ranked_numbers,revision,submitted
    ) values ($1,$2,1,1,$3,'{2}',1,false)`, [EVENT3_MATCH_ID, EVENT_ID, startedAt])
    if (count === 30) {
      await expectDbError(
        db.query("select clear_event3_test_data_v2($1,'stale-test-session')", [EVENT_ID]),
        /live\/test session changed/i,
      )
      await db.query("select clear_event3_test_data_v2($1,$2)", [EVENT_ID, startedAt])
      const clearedTransientRows = await db.query(`select
        (select count(*)::int from event3_cohost_notes where test_session_key=$1) as notes,
        (select count(*)::int from event3_ranking_drafts where session_key=$1) as drafts`, [startedAt])
      assert.deepEqual(clearedTransientRows.rows, [{ notes: 0, drafts: 0 }])
      await db.query(`insert into event3_cohost_notes(
        match_id,event_id,test_mode,test_session_key,scope_type,scope_key,note
      ) values ($1,$2,true,$3,'event','event','temporary cohost note')`, [EVENT3_MATCH_ID, EVENT_ID, startedAt])
      await db.query(`insert into event3_ranking_drafts(
        match_id,event_id,ranker_number,completed_rounds,session_key,ranked_numbers,revision,submitted
      ) values ($1,$2,1,1,$3,'{2}',2,false)`, [EVENT3_MATCH_ID, EVENT_ID, startedAt])
    }
    await db.query(`insert into event3_group_reflections(
      match_id,event_id,ranker_number,ranked_numbers,source_phase,group_round
    ) values ($1,$2,1,'{2}','ranking1',1)`, [EVENT3_MATCH_ID, EVENT_ID])

    const ended = await db.query("select end_event3_test_mode($1) as result", [EVENT_ID])
    assert.equal(ended.rows[0].result.cohost_notes_deleted, 1)
    assert.equal(ended.rows[0].result.ranking_drafts_deleted, 1)
    await expectDbError(
      db.query(`select set_event3_attendance_v2(
        $1,1,true,'auto-join',true,true,$2
      )`, [EVENT_ID, startedAt]),
      /live\/test session changed/i,
    )
    const restored = await db.query(`select
      (select array_agg(participant_number order by participant_number) from event_attendance where event_id=$1) as attendance,
      (select array_agg(participant_number order by participant_number) from organizer_requests where event_id=$1) as requests,
      (select array_agg(participant_number order by participant_number) from organizer_requests where event_id is null) as null_event_requests,
      (select array_agg(ranker_number order by ranker_number) from event3_group_reflections where event_id=$1) as reflections`, [EVENT_ID])
    assert.deepEqual(restored.rows, [{ attendance: [101], requests: [101], null_event_requests: [102], reflections: [101] }])
  }
})

test("variable runtime migration refuses an active legacy Event3 test snapshot", async t => {
  await assert.rejects(
    createFixture(t, {
      beforeVariableRuntime: async db => {
        await db.query(`insert into event_state(
          match_id,current_event_id,phase,current_round,test_mode_active,test_mode_snapshot
        ) values ($1,$2,'setup',1,true,'{"started_at":"legacy-session"}'::jsonb)`, [EVENT3_MATCH_ID, EVENT_ID])
        await db.query(`insert into event3_test_mode_snapshots(match_id,event_id,snapshot)
          values ($1,$2,'{"version":1}'::jsonb)`, [EVENT3_MATCH_ID, EVENT_ID])
      },
    }),
    error => {
      assert.match(String(error?.message || error), /End the active legacy Event3 test session/i)
      return true
    },
  )
})

test("test mode refuses an Event3 state with no current event", async t => {
  const db = await createFixture(t)
  await db.query(`insert into event_state(
    match_id,current_event_id,phase,current_round,test_mode_active
  ) values ($1,null,'setup',1,false)`, [EVENT3_MATCH_ID])
  await expectDbError(
    db.query("select begin_event3_test_mode($1,$2::integer[])", [
      EVENT_ID,
      Array.from({ length: 36 }, (_, index) => index + 1),
    ]),
    /not configured for event/i,
  )
  assert.equal((await db.query("select test_mode_active from event_state where match_id=$1", [EVENT3_MATCH_ID])).rows[0].test_mode_active, false)
})

test("session-locked Event3 auxiliary RPCs validate and mutate only the active roster", async t => {
  const db = await createFixture(t)
  const serviceOnlySignatures = [
    "end_event3_test_mode_v2(integer,text)",
    "clear_event3_test_data_v2(integer,text)",
    "toggle_event3_score_reveal_v2(integer,text,boolean,boolean,text)",
    "toggle_event3_phase2_exclusion_v2(integer,integer,boolean,boolean,text)",
    "set_event3_phase_v2(integer,text,boolean,integer,integer,boolean,text)",
    "start_event3_timer_v2(integer,integer,integer,boolean,text)",
    "stop_event3_timer_v2(integer,boolean,text)",
    "adjust_event3_timer_v2(integer,integer,boolean,text)",
    "replace_event3_admin_ranking_order_v2(integer,integer,integer[],boolean,text)",
    "save_event3_ranking_v2(uuid,integer,integer,integer,integer[],bigint,boolean,boolean,boolean,text)",
    "replace_event3_admin_rankings_v2(integer,integer[],jsonb,boolean,text)",
    "clear_event3_participant_ranking_v2(integer,integer,boolean,text)",
    "clear_event3_rankings_v2(integer,boolean,text)",
    "save_event3_participant_note_v2(integer,integer,integer,text,boolean,text)",
    "submit_event3_mood_check_v2(integer,integer,text,text,boolean,text)",
    "trigger_event3_mood_check_v2(integer,text,integer[],boolean,text)",
    "clear_event3_mood_checks_v2(integer,boolean,text)",
    "dismiss_event3_notification_v2(integer,integer,text,boolean,text)",
    "send_event3_notification_v2(integer,text,integer[],text,text,text,boolean,text)",
    "clear_event3_notifications_v2(integer,boolean,text)",
    "upsert_event3_welcome_messages_v2(integer,jsonb,boolean,text)",
    "delete_event3_welcome_message_v2(integer,integer,boolean,text)",
    "reset_event3_attendance_v2(integer,boolean,text)",
    "edit_event3_feedback_v2(integer,integer,text,integer,jsonb,boolean,text)",
    "clear_event3_feedback_v2(integer,boolean,boolean,boolean,text)",
    "save_event3_cohost_note_v2(integer,text,text,integer,integer,integer,integer,text,text,timestamp with time zone,boolean,text)",
    "replace_event3_participant_v2(uuid,uuid,integer,integer,integer,jsonb,jsonb,boolean,text)",
    "swap_event3_match_partner_v2(uuid,integer,text,integer,integer,integer,integer,jsonb,jsonb,boolean,text)",
    "replace_event3_algorithm_match_partner_v2(uuid,uuid,integer,integer,integer,integer,integer,jsonb,jsonb,boolean,boolean,text)",
  ]
  for (const signature of serviceOnlySignatures) {
    const privileges = await db.query(`select
      has_function_privilege('anon',$1,'execute') as anon,
      has_function_privilege('authenticated',$1,'execute') as authenticated,
      has_function_privilege('service_role',$1,'execute') as service_role`, [`public.${signature}`])
    assert.deepEqual(privileges.rows, [{ anon: false, authenticated: false, service_role: true }])
  }
  await db.query(`insert into event_state(
    match_id,current_event_id,phase,current_round,test_mode_active,
    phase2_score_revealed,phase3_score_revealed
  ) values ($1,$2,'setup',1,false,false,false)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query("select set_event3_event_format($1,$2,'choice_only_three_groups')", [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into event3_participants(match_id,event_id,participant_number,position)
    select $1,$2,number,number - 1 from generate_series(1,4) number`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into session_assignments(match_id,event_id,round,table_number,participant_id)
    select $1,$2,1,1,number from generate_series(1,4) number`, [EVENT3_MATCH_ID, EVENT_ID])

  const createdCohostNote = await db.query(`select save_event3_cohost_note_v2(
    $1,'event','event',null,null,null,null,'  Doors open at seven  ','admin3',null,false,null
  ) as result`, [EVENT_ID])
  assert.equal(createdCohostNote.rows[0].result.note.note, "Doors open at seven")
  assert.equal(createdCohostNote.rows[0].result.note.test_session_key, "")
  const firstNoteUpdatedAt = createdCohostNote.rows[0].result.note.updated_at
  await expectDbError(
    db.query(`select save_event3_cohost_note_v2(
      $1,'event','event',null,null,null,null,'conflict','admin3',null,false,null
    )`, [EVENT_ID]),
    /co-host note changed/i,
  )
  const updatedCohostNote = await db.query(`select save_event3_cohost_note_v2(
    $1,'event','event',null,null,null,null,'Doors open at eight','event3-cohost',$2,false,null
  ) as result`, [EVENT_ID, firstNoteUpdatedAt])
  assert.equal(updatedCohostNote.rows[0].result.note.note, "Doors open at eight")
  await expectDbError(
    db.query(`select save_event3_cohost_note_v2(
      $1,'participant','participant:99',null,null,99,null,'missing','event3-cohost',null,false,null
    )`, [EVENT_ID]),
    /not enrolled in the active roster/i,
  )
  await expectDbError(
    db.query(`select save_event3_cohost_note_v2(
      $1,'table','table:1:99',1,99,null,null,'missing','event3-cohost',null,false,null
    )`, [EVENT_ID]),
    /table does not exist/i,
  )
  await expectDbError(
    db.query(`select save_event3_cohost_note_v2(
      $1,'pair','pair:20:1-2',20,null,1,2,'not paired','event3-cohost',null,false,null
    )`, [EVENT_ID]),
    /not a current reciprocal meeting/i,
  )
  const participantCohostNote = await db.query(`select save_event3_cohost_note_v2(
    $1,'participant','participant:1',null,null,1,null,'Follow up','event3-cohost',null,false,null
  ) as result`, [EVENT_ID])
  const deletedCohostNote = await db.query(`select save_event3_cohost_note_v2(
    $1,'participant','participant:1',null,null,1,null,'   ','event3-cohost',$2,false,null
  ) as result`, [EVENT_ID, participantCohostNote.rows[0].result.note.updated_at])
  assert.deepEqual(
    { deleted: deletedCohostNote.rows[0].result.deleted, note: deletedCohostNote.rows[0].result.note },
    { deleted: true, note: null },
  )

  const revealed = await db.query(`select toggle_event3_score_reveal_v2(
    $1,'phase2',true,false,null
  ) as result`, [EVENT_ID])
  assert.equal(revealed.rows[0].result.revealed, true)
  const phaseStarted = await db.query(`select set_event3_phase_v2(
    $1,'round1',true,null,1,false,null
  ) as result`, [EVENT_ID])
  assert.deepEqual(
    {
      phase: phaseStarted.rows[0].result.phase,
      timer_active: phaseStarted.rows[0].result.timer_active,
      timer_duration: phaseStarted.rows[0].result.timer_duration,
      timer_round: phaseStarted.rows[0].result.timer_round,
    },
    { phase: "round1", timer_active: true, timer_duration: 1800, timer_round: 1 },
  )
  const adjustedTimer = await db.query("select adjust_event3_timer_v2($1,-60,false,null) as result", [EVENT_ID])
  assert.equal(adjustedTimer.rows[0].result.timer_duration, 1740)
  await db.query("select stop_event3_timer_v2($1,false,null)", [EVENT_ID])
  await expectDbError(
    db.query("select adjust_event3_timer_v2($1,60,false,null)", [EVENT_ID]),
    /timer is not active/i,
  )
  await db.query("select set_event3_phase_v2($1,'setup',false,null,null,false,null)", [EVENT_ID])
  const restartedTimer = await db.query("select start_event3_timer_v2($1,3,null,false,null) as result", [EVENT_ID])
  assert.equal(restartedTimer.rows[0].result.timer_duration, 600)
  await db.query("select stop_event3_timer_v2($1,false,null)", [EVENT_ID])
  await expectDbError(
    db.query("select set_event3_phase_v2($1,'unknown',null,null,null,false,null)", [EVENT_ID]),
    /unknown Event3 phase/i,
  )
  await db.query("update event_state set phase='ranking1' where match_id=$1", [EVENT3_MATCH_ID])

  const participantDraft = await db.query(`select save_event3_ranking_v2(
    $1,$2,3,1,'{1,2,4}'::integer[],1,true,false,false,null
  ) as result`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(
    { saved: participantDraft.rows[0].result.saved, complete: participantDraft.rows[0].result.complete },
    { saved: true, complete: false },
  )
  assert.deepEqual((await db.query(`select ranker_number,session_key,submitted
    from event3_ranking_drafts where ranker_number=3`)).rows, [
    { ranker_number: 3, session_key: "live", submitted: false },
  ])

  const savedNote = await db.query(`select save_event3_participant_note_v2(
    $1,1,2,'  remembers the coast  ',false,null
  ) as result`, [EVENT_ID])
  assert.equal(savedNote.rows[0].result.saved, true)
  assert.deepEqual((await db.query(`select participant_number,about_number,note
    from event3_participant_notes`)).rows, [{ participant_number: 1, about_number: 2, note: "remembers the coast" }])
  await expectDbError(
    db.query("select save_event3_participant_note_v2($1,1,99,'no',false,null)", [EVENT_ID]),
    /both note participants.*active.*roster/i,
  )

  const ranking = await db.query(`select replace_event3_admin_ranking_order_v2(
    $1,1,'{3,2,4}'::integer[],false,null
  ) as result`, [EVENT_ID])
  assert.equal(ranking.rows[0].result.count, 3)
  await db.query(`update participant_rankings set auto_saved=true
    where match_id=$1 and event_id=$2 and ranker_number=1 and ranked_number=2`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`select replace_event3_admin_ranking_order_v2(
    $1,1,'{2,4,3}'::integer[],false,null
  )`, [EVENT_ID])
  const rankingRows = await db.query(`select ranked_number,rank,auto_saved
    from participant_rankings where match_id=$1 and event_id=$2 and ranker_number=1 order by rank`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.deepEqual(rankingRows.rows, [
    { ranked_number: 2, rank: 1, auto_saved: true },
    { ranked_number: 4, rank: 2, auto_saved: false },
    { ranked_number: 3, rank: 3, auto_saved: false },
  ])
  await db.query(`insert into event3_ranking_drafts(
    match_id,event_id,ranker_number,completed_rounds,session_key,ranked_numbers,revision
  ) values ($1,$2,1,1,'live','{2,4,3}'::integer[],1)`, [EVENT3_MATCH_ID, EVENT_ID])
  const clearedParticipantRanking = await db.query(`select clear_event3_participant_ranking_v2(
    $1,1,false,null
  ) as result`, [EVENT_ID])
  assert.deepEqual(
    {
      deleted: clearedParticipantRanking.rows[0].result.deleted,
      drafts_deleted: clearedParticipantRanking.rows[0].result.drafts_deleted,
    },
    { deleted: 3, drafts_deleted: 1 },
  )
  assert.equal((await db.query(`select count(*)::int as count from participant_rankings
    where match_id=$1 and event_id=$2 and ranker_number=1`, [EVENT3_MATCH_ID, EVENT_ID])).rows[0].count, 0)
  await db.query(`select replace_event3_admin_ranking_order_v2(
    $1,1,'{2,4,3}'::integer[],false,null
  )`, [EVENT_ID])
  await db.query(`select replace_event3_admin_ranking_order_v2(
    $1,2,'{1,3,4}'::integer[],false,null
  )`, [EVENT_ID])
  await db.query(`insert into event3_ranking_drafts(
    match_id,event_id,ranker_number,completed_rounds,session_key,ranked_numbers,revision
  ) values
    ($1,$2,1,1,'live','{2,4,3}'::integer[],2),
    ($1,$2,2,1,'live','{1,3,4}'::integer[],1)`, [EVENT3_MATCH_ID, EVENT_ID])
  const clearedRankings = await db.query("select clear_event3_rankings_v2($1,false,null) as result", [EVENT_ID])
  assert.deepEqual(
    {
      deleted: clearedRankings.rows[0].result.deleted,
      drafts_deleted: clearedRankings.rows[0].result.drafts_deleted,
    },
    { deleted: 6, drafts_deleted: 3 },
  )
  assert.deepEqual((await db.query(`select
    (select count(*)::int from participant_rankings where match_id=$1 and event_id=$2) as rankings,
    (select count(*)::int from event3_ranking_drafts where match_id=$1 and event_id=$2 and session_key='live') as drafts`,
  [EVENT3_MATCH_ID, EVENT_ID])).rows, [{ rankings: 0, drafts: 0 }])
  const invalidBulkRows = JSON.stringify([
    ...[2, 4, 3].map((rankedNumber, index) => ({ ranker_number: 1, ranked_number: rankedNumber, rank: index + 1 })),
    ...[1, 3].map((rankedNumber, index) => ({ ranker_number: 2, ranked_number: rankedNumber, rank: index + 1 })),
  ])
  await expectDbError(
    db.query(`select replace_event3_admin_rankings_v2(
      $1,'{1,2}'::integer[],$2::jsonb,false,null
    )`, [EVENT_ID, invalidBulkRows]),
    /each participant met so far exactly once/i,
  )
  assert.equal((await db.query(`select count(*)::int as count from participant_rankings
    where match_id=$1 and event_id=$2`, [EVENT3_MATCH_ID, EVENT_ID])).rows[0].count, 0)
  const bulkRows = JSON.stringify([
    ...[2, 4, 3].map((rankedNumber, index) => ({ ranker_number: 1, ranked_number: rankedNumber, rank: index + 1 })),
    ...[1, 3, 4].map((rankedNumber, index) => ({ ranker_number: 2, ranked_number: rankedNumber, rank: index + 1 })),
  ])
  const replacedBulk = await db.query(`select replace_event3_admin_rankings_v2(
    $1,'{1,2}'::integer[],$2::jsonb,false,null
  ) as result`, [EVENT_ID, bulkRows])
  assert.deepEqual(
    { rankers: replacedBulk.rows[0].result.rankers, saved: replacedBulk.rows[0].result.saved },
    { rankers: 2, saved: 6 },
  )
  await db.query("select clear_event3_rankings_v2($1,false,null)", [EVENT_ID])
  await expectDbError(
    db.query("select replace_event3_admin_ranking_order_v2($1,1,'{2,3}'::integer[],false,null)", [EVENT_ID]),
    /each participant met so far exactly once/i,
  )
  await db.query("update event_state set phase='round2' where match_id=$1", [EVENT3_MATCH_ID])
  await expectDbError(
    db.query("select replace_event3_admin_ranking_order_v2($1,1,'{2,3,4}'::integer[],false,null)", [EVENT_ID]),
    /active ranking phase/i,
  )
  await db.query("update event_state set phase='ranking1' where match_id=$1", [EVENT3_MATCH_ID])

  await db.query(`insert into event3_matches(
    match_id,event_id,participant_number,phase2_partner
  ) values
    ($1,$2,1,2),($1,$2,2,1),($1,$2,3,null),($1,$2,4,null)`, [EVENT3_MATCH_ID, EVENT_ID])
  await expectDbError(
    db.query(`select save_event3_cohost_note_v2(
      $1,'pair','pair:20:1-2',20,null,1,2,'No table yet','event3-cohost',null,false,null
    )`, [EVENT_ID]),
    /does not share its current one-to-one table/i,
  )
  await db.query(`insert into session_assignments(
    match_id,event_id,round,table_number,participant_id
  ) values ($1,$2,20,5,1),($1,$2,20,5,2)`, [EVENT3_MATCH_ID, EVENT_ID])
  const pairCohostNote = await db.query(`select save_event3_cohost_note_v2(
    $1,'pair','pair:20:1-2',20,null,1,2,'Pair follow-up','event3-cohost',null,false,null
  ) as result`, [EVENT_ID])
  assert.equal(pairCohostNote.rows[0].result.note.scope_key, "pair:20:1-2")
  await db.query(`select save_event3_cohost_note_v2(
    $1,'pair','pair:20:1-2',20,null,1,2,'','event3-cohost',$2,false,null
  )`, [EVENT_ID, pairCohostNote.rows[0].result.note.updated_at])
  const editedFeedback = await db.query(`select edit_event3_feedback_v2(
    $1,1,'phase2',2,'{"wantConnect":true}'::jsonb,false,null
  ) as result`, [EVENT_ID])
  assert.equal(editedFeedback.rows[0].result.partner_number, 2)
  await expectDbError(
    db.query(`select edit_event3_feedback_v2(
      $1,1,'phase2',4,'{"wantConnect":false}'::jsonb,false,null
    )`, [EVENT_ID]),
    /feedback partner changed/i,
  )
  await expectDbError(
    db.query(`select edit_event3_feedback_v2(
      $1,3,'phase2',4,'{"wantConnect":false}'::jsonb,false,null
    )`, [EVENT_ID]),
    /reciprocal partner/i,
  )
  await db.query(`insert into event3_group_member_feedback(
    match_id,event_id,group_round,reviewer_number,member_number,experience,is_test_mode
  ) values
    ($1,$2,1,1,2,'good',false),
    ($1,$2,1,1,2,'great',true)`, [EVENT3_MATCH_ID, EVENT_ID])
  const clearedFeedback = await db.query(`select clear_event3_feedback_v2(
    $1,true,false,false,null
  ) as result`, [EVENT_ID])
  assert.equal(clearedFeedback.rows[0].result.group_rows_deleted, 1)
  assert.equal((await db.query(`select count(*)::int as count
    from event3_group_member_feedback where is_test_mode=true`)).rows[0].count, 1)
  assert.equal((await db.query(`select count(*)::int as count
    from event3_matches where phase2_feedback is not null`)).rows[0].count, 0)

  const firstMood = await db.query(`select trigger_event3_mood_check_v2(
    $1,'check-1','{1,2}'::integer[],false,null
  ) as result`, [EVENT_ID])
  assert.equal(firstMood.rows[0].result.sent_to, 2)
  const secondMood = await db.query(`select trigger_event3_mood_check_v2(
    $1,'check-2','{1,2,3}'::integer[],false,null
  ) as result`, [EVENT_ID])
  assert.deepEqual(
    { sent_to: secondMood.rows[0].result.sent_to, skipped_pending: secondMood.rows[0].result.skipped_pending },
    { sent_to: 1, skipped_pending: 2 },
  )
  const submittedMood = await db.query(`select submit_event3_mood_check_v2(
    $1,1,'check-1','happy',false,null
  ) as result`, [EVENT_ID])
  assert.equal(submittedMood.rows[0].result.saved, true)
  const retriedMood = await db.query(`select submit_event3_mood_check_v2(
    $1,1,'check-1','happy',false,null
  ) as result`, [EVENT_ID])
  assert.equal(retriedMood.rows[0].result.saved, false)
  await expectDbError(
    db.query("select submit_event3_mood_check_v2($1,1,'check-1','neutral',false,null)", [EVENT_ID]),
    /already answered/i,
  )
  const clearedMoods = await db.query("select clear_event3_mood_checks_v2($1,false,null) as result", [EVENT_ID])
  assert.equal(clearedMoods.rows[0].result.deleted, 3)

  const sentNotification = await db.query(`select send_event3_notification_v2(
    $1,'notif-1','{1,2}'::integer[],'  Move tables  ','  Table 2  ','clock',false,null
  ) as result`, [EVENT_ID])
  assert.equal(sentNotification.rows[0].result.sent_to, 2)
  const dismissed = await db.query(`select dismiss_event3_notification_v2(
    $1,1,'notif-1',false,null
  ) as result`, [EVENT_ID])
  assert.equal(dismissed.rows[0].result.dismissed, true)
  assert.equal((await db.query(`select count(*)::int as count from event3_notifications
    where notif_id='notif-1' and seen_at is not null`)).rows[0].count, 1)
  await expectDbError(
    db.query(`select send_event3_notification_v2(
      $1,'notif-bad','{99}'::integer[],'Title',null,'info',false,null
    )`, [EVENT_ID]),
    /active Event3 roster/i,
  )
  const clearedNotifications = await db.query("select clear_event3_notifications_v2($1,false,null) as result", [EVENT_ID])
  assert.equal(clearedNotifications.rows[0].result.deleted, 2)

  const welcomeRows = JSON.stringify([
    { participant_number: 1, welcome_message: " Welcome one ", generated_by: "admin", anchor_used: "hobbies" },
    { participant_number: 2, welcome_message: "Welcome two", generated_by: "system", anchor_used: null },
  ])
  const savedWelcomes = await db.query(`select upsert_event3_welcome_messages_v2(
    $1,$2::jsonb,false,null
  ) as result`, [EVENT_ID, welcomeRows])
  assert.equal(savedWelcomes.rows[0].result.saved, 2)
  const updatedWelcome = JSON.stringify([
    { participant_number: 1, welcome_message: "Updated welcome", generated_by: "admin", anchor_used: "weekend" },
  ])
  await db.query("select upsert_event3_welcome_messages_v2($1,$2::jsonb,false,null)", [EVENT_ID, updatedWelcome])
  assert.deepEqual((await db.query(`select participant_number,welcome_message,anchor_used
    from event3_ai_welcome_messages order by participant_number`)).rows, [
    { participant_number: 1, welcome_message: "Updated welcome", anchor_used: "weekend" },
    { participant_number: 2, welcome_message: "Welcome two", anchor_used: null },
  ])
  const deletedWelcome = await db.query("select delete_event3_welcome_message_v2($1,2,false,null) as result", [EVENT_ID])
  assert.equal(deletedWelcome.rows[0].result.deleted, true)

  await db.query(`insert into event_attendance(match_id,event_id,participant_number,attended,updated_by)
    values ($1,$2,1,true,'event3-host'),($1,$2,2,false,'event3-host')`, [ATTENDANCE_MATCH_ID, EVENT_ID])
  const resetAttendance = await db.query("select reset_event3_attendance_v2($1,false,null) as result", [EVENT_ID])
  assert.equal(resetAttendance.rows[0].result.deleted, 2)

  const replacedParticipant = await db.query(`select replace_event3_participant_v2(
    $1,$2,$3,1,2,'[]'::jsonb,'[]'::jsonb,false,null
  ) as result`, [EVENT3_MATCH_ID, STATIC_MATCH_ID, EVENT_ID])
  assert.equal(replacedParticipant.rows[0].result.delegate, "replace_event3_participant")
  const swappedPartner = await db.query(`select swap_event3_match_partner_v2(
    $1,$2,'phase2',1,3,2,4,'{}'::jsonb,null,false,null
  ) as result`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.equal(swappedPartner.rows[0].result.delegate, "swap_event3_match_partner")
  const replacedAlgorithmPartner = await db.query(`select replace_event3_algorithm_match_partner_v2(
    $1,$2,$3,1,3,2,4,'{}'::jsonb,null,true,false,null
  ) as result`, [EVENT3_MATCH_ID, STATIC_MATCH_ID, EVENT_ID])
  assert.equal(replacedAlgorithmPartner.rows[0].result.delegate, "replace_event3_algorithm_match_partner")

  const begin = await db.query("select begin_event3_test_mode($1,$2::integer[]) as result", [EVENT_ID, Array.from({ length: 16 }, (_, index) => index + 1)])
  assert.equal(begin.rows[0].result.selected_count, 16)
  const session = await db.query("select test_mode_snapshot->>'started_at' as started_at from event_state where match_id=$1", [EVENT3_MATCH_ID])
  const startedAt = session.rows[0].started_at
  await expectDbError(
    db.query(`select save_event3_cohost_note_v2(
      $1,'event','event',null,null,null,null,'stale','event3-cohost',$2,false,null
    )`, [EVENT_ID, updatedCohostNote.rows[0].result.note.updated_at]),
    /live\/test session changed/i,
  )
  const testCohostNote = await db.query(`select save_event3_cohost_note_v2(
    $1,'event','event',null,null,null,null,'Test session note','event3-cohost',null,true,$2
  ) as result`, [EVENT_ID, startedAt])
  assert.equal(testCohostNote.rows[0].result.note.test_session_key, startedAt)
  await expectDbError(
    db.query("select save_event3_participant_note_v2($1,1,2,'stale',false,null)", [EVENT_ID]),
    /live\/test session changed/i,
  )
  await expectDbError(
    db.query("select set_event3_phase_v2($1,'round1',true,1800,1,false,null)", [EVENT_ID]),
    /live\/test session changed/i,
  )
  await expectDbError(
    db.query(`select edit_event3_feedback_v2(
      $1,1,'phase2',2,'{}'::jsonb,false,null
    )`, [EVENT_ID]),
    /live\/test session changed/i,
  )
  await expectDbError(
    db.query("select clear_event3_participant_ranking_v2($1,1,false,null)", [EVENT_ID]),
    /live\/test session changed/i,
  )
  await expectDbError(
    db.query("select clear_event3_rankings_v2($1,false,null)", [EVENT_ID]),
    /live\/test session changed/i,
  )
  await expectDbError(
    db.query(`select replace_event3_admin_rankings_v2(
      $1,'{1,2}'::integer[],$2::jsonb,false,null
    )`, [EVENT_ID, bulkRows]),
    /live\/test session changed/i,
  )
  await expectDbError(
    db.query(`select save_event3_ranking_v2(
      $1,$2,1,1,'{2,3,4}'::integer[],2,true,false,false,null
    )`, [EVENT3_MATCH_ID, EVENT_ID]),
    /live\/test session changed/i,
  )
  await expectDbError(
    db.query("select toggle_event3_phase2_exclusion_v2($1,1,false,false,null)", [EVENT_ID]),
    /live\/test session changed/i,
  )
  await expectDbError(
    db.query(`select replace_event3_participant_v2(
      $1,$2,$3,1,2,'[]'::jsonb,'[]'::jsonb,false,null
    )`, [EVENT3_MATCH_ID, STATIC_MATCH_ID, EVENT_ID]),
    /live\/test session changed/i,
  )
  await expectDbError(
    db.query(`select swap_event3_match_partner_v2(
      $1,$2,'phase2',1,3,2,4,'{}'::jsonb,null,false,null
    )`, [EVENT3_MATCH_ID, EVENT_ID]),
    /live\/test session changed/i,
  )
  await expectDbError(
    db.query(`select replace_event3_algorithm_match_partner_v2(
      $1,$2,$3,1,3,2,4,'{}'::jsonb,null,true,false,null
    )`, [EVENT3_MATCH_ID, STATIC_MATCH_ID, EVENT_ID]),
    /live\/test session changed/i,
  )
  await db.query("select save_event3_participant_note_v2($1,1,2,'test note',true,$2)", [EVENT_ID, startedAt])
  await db.query(`select send_event3_notification_v2(
    $1,'test-notif','{1}'::integer[],'Test',null,'info',true,$2
  )`, [EVENT_ID, startedAt])
  const clearedTestFeedback = await db.query(`select clear_event3_feedback_v2(
    $1,true,true,true,$2
  ) as result`, [EVENT_ID, startedAt])
  assert.equal(clearedTestFeedback.rows[0].result.group_rows_deleted, 1)
  await db.query(`insert into event3_group_member_feedback(
    match_id,event_id,group_round,reviewer_number,member_number,experience,is_test_mode
  ) values ($1,$2,1,1,2,'good',true)`, [EVENT3_MATCH_ID, EVENT_ID])
  await expectDbError(
    db.query("select end_event3_test_mode_v2($1,'stale-test-session')", [EVENT_ID]),
    /live\/test session changed/i,
  )
  const endedTest = await db.query("select end_event3_test_mode_v2($1,$2) as result", [EVENT_ID, startedAt])
  assert.equal(endedTest.rows[0].result.group_feedback_deleted, 1)
  await expectDbError(
    db.query("select reset_event3_attendance_v2($1,true,$2)", [EVENT_ID, startedAt]),
    /live\/test session changed/i,
  )
  assert.deepEqual((await db.query(`select participant_number,about_number,note
    from event3_participant_notes order by participant_number,about_number`)).rows, [
    { participant_number: 1, about_number: 2, note: "remembers the coast" },
  ])
  assert.equal((await db.query("select count(*)::int as count from event3_notifications")).rows[0].count, 0)
  assert.deepEqual((await db.query(`select test_mode,test_session_key,note
    from event3_cohost_notes order by test_mode`)).rows, [
    { test_mode: false, test_session_key: "", note: "Doors open at eight" },
  ])
})

test("bulk admin rankings use the same exact ballot contract for classic Event3", async t => {
  const db = await createFixture(t)
  await db.query(`insert into event_state(
    match_id,current_event_id,phase,current_round,test_mode_active
  ) values ($1,$2,'ranking1',1,false)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into event3_participants(match_id,event_id,participant_number,position)
    select $1,$2,number,number - 1 from generate_series(1,4) number`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into session_assignments(match_id,event_id,round,table_number,participant_id)
    select $1,$2,1,1,number from generate_series(1,4) number`, [EVENT3_MATCH_ID, EVENT_ID])
  const excluded = await db.query(`select toggle_event3_phase2_exclusion_v2(
    $1,1,false,false,null
  ) as result`, [EVENT_ID])
  assert.equal(excluded.rows[0].result.phase2_excluded, true)
  await expectDbError(
    db.query("select toggle_event3_phase2_exclusion_v2($1,1,false,false,null)", [EVENT_ID]),
    /exclusion changed before it was saved/i,
  )
  const included = await db.query(`select toggle_event3_phase2_exclusion_v2(
    $1,1,true,false,null
  ) as result`, [EVENT_ID])
  assert.equal(included.rows[0].result.phase2_excluded, false)
  const rows = JSON.stringify([
    ...[4, 2, 3].map((rankedNumber, index) => ({ ranker_number: 1, ranked_number: rankedNumber, rank: index + 1 })),
    ...[3, 1, 4].map((rankedNumber, index) => ({ ranker_number: 2, ranked_number: rankedNumber, rank: index + 1 })),
  ])
  const result = await db.query(`select replace_event3_admin_rankings_v2(
    $1,'{1,2}'::integer[],$2::jsonb,false,null
  ) as result`, [EVENT_ID, rows])
  assert.deepEqual(
    { rankers: result.rows[0].result.rankers, saved: result.rows[0].result.saved },
    { rankers: 2, saved: 6 },
  )
  assert.deepEqual((await db.query(`select ranker_number,ranked_number,rank
    from participant_rankings order by ranker_number,rank`)).rows, [
    { ranker_number: 1, ranked_number: 4, rank: 1 },
    { ranker_number: 1, ranked_number: 2, rank: 2 },
    { ranker_number: 1, ranked_number: 3, rank: 3 },
    { ranker_number: 2, ranked_number: 3, rank: 1 },
    { ranker_number: 2, ranked_number: 1, rank: 2 },
    { ranker_number: 2, ranked_number: 4, rank: 3 },
  ])
})
