import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"
import { PGlite } from "@electric-sql/pglite"

test("round-40 cohost note migration upgrades an already-migrated database", async () => {
  const db = new PGlite()
  try {
    await db.exec(`
      create table public.event3_cohost_notes (
        id bigint generated by default as identity primary key,
        scope_type text not null check (scope_type in ('event', 'table', 'participant', 'pair')),
        scope_key text not null,
        round smallint constraint event3_cohost_notes_round_check check (round in (1, 2, 3, 20, 30)),
        table_number integer,
        participant_number integer,
        participant2_number integer,
        note text not null,
        constraint event3_cohost_notes_scope_shape check (
          (scope_type = 'event' and round is null and table_number is null
            and participant_number is null and participant2_number is null)
          or (scope_type = 'table' and round is not null and table_number is not null
            and participant_number is null and participant2_number is null)
          or (scope_type = 'participant' and round is null and table_number is null
            and participant_number is not null and participant2_number is null)
          or (scope_type = 'pair' and round in (20, 30) and table_number is null
            and participant_number is not null and participant2_number is not null
            and participant_number < participant2_number)
        )
      );
    `)

    const migration = await readFile(
      new URL("../../supabase/migrations/20260901134058_extend_event3_cohost_notes_round_40.sql", import.meta.url),
      "utf8",
    )
    await db.exec(migration)
    await db.exec(migration)

    await db.exec(`
      insert into public.event3_cohost_notes
        (scope_type,scope_key,round,table_number,note)
      values ('table','table:40:9',40,9,'third table note');
      insert into public.event3_cohost_notes
        (scope_type,scope_key,round,participant_number,participant2_number,note)
      values ('pair','pair:40:1-22',40,1,22,'third pair note');
    `)

    const rows = (await db.query(`
      select scope_type,round,table_number,participant_number,participant2_number
      from public.event3_cohost_notes
      order by scope_type
    `)).rows
    assert.deepEqual(rows, [
      { scope_type: "pair", round: 40, table_number: null, participant_number: 1, participant2_number: 22 },
      { scope_type: "table", round: 40, table_number: 9, participant_number: null, participant2_number: null },
    ])

    await assert.rejects(
      db.exec(`insert into public.event3_cohost_notes
        (scope_type,scope_key,round,participant_number,participant2_number,note)
        values ('pair','pair:3:1-22',3,1,22,'invalid pair round')`),
      /event3_cohost_notes_scope_shape/i,
    )
  } finally {
    await db.close()
  }
})
