import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"
import { PGlite } from "@electric-sql/pglite"

const EVENT3_MATCH_ID = "00000000-0000-0000-0000-000000000003"
const EVENT_ID = 26
const STARTED_AT = "2026-09-06T00:00:00.000Z"
const migrationUrl = new URL(
  "../../supabase/migrations/20260906014852_event3_group_coordinator_elections.sql",
  import.meta.url,
)
const quickResolutionMigrationUrl = new URL(
  "../../supabase/migrations/20260906025812_event3_group_coordinator_quick_resolution.sql",
  import.meta.url,
)

async function expectDbError(promise, pattern) {
  await assert.rejects(promise, error => {
    assert.match(String(error?.message || error), pattern)
    return true
  })
}

async function createFixture(t) {
  const db = new PGlite()
  t.after(() => db.close())
  await db.exec(`
    create role anon;
    create role authenticated;
    create role service_role bypassrls;

    create table public.event_state (
      match_id uuid primary key,
      current_event_id integer,
      test_mode_active boolean not null default false,
      test_mode_snapshot jsonb
    );
    create table public.session_assignments (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      round smallint not null,
      table_number integer not null,
      participant_id integer not null,
      unique (match_id, event_id, round, participant_id)
    );

    create or replace function public.assert_event3_auxiliary_session(
      p_event_id integer,
      p_expected_test_mode boolean,
      p_expected_started_at text
    ) returns void
    language plpgsql
    security invoker
    set search_path = ''
    as $fixture$
    declare
      v_state public.event_state%rowtype;
    begin
      select state.* into v_state
      from public.event_state state
      where state.match_id = '${EVENT3_MATCH_ID}'::uuid;
      if not found or v_state.current_event_id is distinct from p_event_id then
        raise exception 'Event3 session changed' using errcode = '55000';
      end if;
      if v_state.test_mode_active is distinct from p_expected_test_mode then
        raise exception 'Event3 test mode changed' using errcode = '55000';
      end if;
      if p_expected_test_mode and v_state.test_mode_snapshot ->> 'started_at' is distinct from p_expected_started_at then
        raise exception 'Event3 test session changed' using errcode = '55000';
      end if;
    end;
    $fixture$;

    insert into public.event_state(match_id,current_event_id,test_mode_active,test_mode_snapshot)
    values ('${EVENT3_MATCH_ID}',${EVENT_ID},false,null);
    insert into public.session_assignments(match_id,event_id,round,table_number,participant_id)
    values
      ('${EVENT3_MATCH_ID}',${EVENT_ID},1,1,1),
      ('${EVENT3_MATCH_ID}',${EVENT_ID},1,1,2),
      ('${EVENT3_MATCH_ID}',${EVENT_ID},1,1,3),
      ('${EVENT3_MATCH_ID}',${EVENT_ID},1,2,4),
      ('${EVENT3_MATCH_ID}',${EVENT_ID},1,2,5);
  `)
  await db.exec(await readFile(migrationUrl, "utf8"))
  await db.exec(await readFile(quickResolutionMigrationUrl, "utf8"))
  return db
}

async function coordinate(db, {
  participant,
  operation,
  candidate = null,
  content = null,
  testMode = false,
  startedAt = null,
  eventId = EVENT_ID,
}) {
  const result = await db.query(`select public.manage_event3_group_coordination_v1(
    $1::integer,$2::smallint,$3::integer,$4::text,$5::integer,$6::jsonb,$7::boolean,$8::text
  ) as state`, [eventId, 1, participant, operation, candidate, content ? JSON.stringify(content) : null, testMode, startedAt])
  return result.rows[0].state
}

async function coordinateQuickly(db, {
  participant,
  operation,
  candidate = null,
  testMode = false,
  startedAt = null,
  eventId = EVENT_ID,
}) {
  const result = await db.query(`select public.quick_resolve_event3_group_coordination_v1(
    $1::integer,$2::smallint,$3::integer,$4::text,$5::integer,$6::boolean,$7::text
  ) as state`, [eventId, 1, participant, operation, candidate, testMode, startedAt])
  return result.rows[0].state
}

test("group coordinator migration keeps ballots private and the RPC service-role-only", async t => {
  const [migration, quickResolutionMigration] = await Promise.all([
    readFile(migrationUrl, "utf8"),
    readFile(quickResolutionMigrationUrl, "utf8"),
  ])
  assert.match(migration, /alter table public\.event3_group_coordination enable row level security/i)
  assert.match(migration, /alter table public\.event3_group_coordinator_votes enable row level security/i)
  assert.match(migration, /revoke all on table public\.event3_group_coordinator_votes from public, anon, authenticated/i)
  assert.match(migration, /security invoker[\s\S]*set search_path = ''/i)
  assert.match(migration, /pg_advisory_xact_lock/i)
  assert.match(migration, /grant execute[\s\S]*to service_role/i)
  assert.match(quickResolutionMigration, /security invoker[\s\S]*set search_path = ''/i)
  assert.match(quickResolutionMigration, /pg_advisory_xact_lock/i)
  assert.match(quickResolutionMigration, /grant execute[\s\S]*to service_role/i)

  const db = await createFixture(t)
  const privileges = await db.query(`select
    has_table_privilege('anon','public.event3_group_coordinator_votes','select') as anon_reads_votes,
    has_table_privilege('authenticated','public.event3_group_coordination','select') as user_reads_state,
    has_function_privilege(
      'anon',
      'public.manage_event3_group_coordination_v1(integer,smallint,integer,text,integer,jsonb,boolean,text)',
      'execute'
    ) as anon_executes,
    has_function_privilege(
      'service_role',
      'public.manage_event3_group_coordination_v1(integer,smallint,integer,text,integer,jsonb,boolean,text)',
      'execute'
    ) as service_executes,
    has_function_privilege(
      'anon',
      'public.quick_resolve_event3_group_coordination_v1(integer,smallint,integer,text,integer,boolean,text)',
      'execute'
    ) as anon_quick_resolves,
    has_function_privilege(
      'service_role',
      'public.quick_resolve_event3_group_coordination_v1(integer,smallint,integer,text,integer,boolean,text)',
      'execute'
    ) as service_quick_resolves`)
  assert.deepEqual(privileges.rows, [{
    anon_reads_votes: false,
    user_reads_state: false,
    anon_executes: false,
    service_executes: true,
    anon_quick_resolves: false,
    service_quick_resolves: true,
  }])
})

test("a table can safely finish voting early, appoint its pick, or draw a random leader", async t => {
  const db = await createFixture(t)

  await coordinate(db, { participant: 1, operation: "open" })
  await expectDbError(
    coordinateQuickly(db, { participant: 1, operation: "finalize" }),
    /at least one vote/i,
  )
  await coordinate(db, { participant: 1, operation: "vote", candidate: 2 })
  const finalized = await coordinateQuickly(db, { participant: 3, operation: "finalize" })
  assert.equal(finalized.status, "elected")
  assert.equal(finalized.coordinator_number, 2)

  await coordinate(db, { participant: 1, operation: "revolt" })
  await expectDbError(
    coordinateQuickly(db, { participant: 3, operation: "direct", candidate: 4 }),
    /not at this table/i,
  )
  await expectDbError(
    coordinateQuickly(db, { participant: 3, operation: "direct", candidate: 1 }),
    /vote for the candidate/i,
  )
  await coordinate(db, { participant: 3, operation: "vote", candidate: 1 })
  const directlySelected = await coordinateQuickly(db, {
    participant: 3,
    operation: "direct",
    candidate: 1,
  })
  assert.equal(directlySelected.status, "elected")
  assert.equal(directlySelected.coordinator_number, 1)

  await coordinate(db, { participant: 2, operation: "revolt" })
  const randomlySelected = await coordinateQuickly(db, { participant: 3, operation: "random" })
  assert.equal(randomlySelected.status, "elected")
  assert.ok([2, 3].includes(randomlySelected.coordinator_number))
  assert.notEqual(randomlySelected.coordinator_number, 1)

  await coordinate(db, { participant: 4, operation: "open" })
  const otherTableRandom = await coordinateQuickly(db, { participant: 5, operation: "random" })
  assert.ok([4, 5].includes(otherTableRandom.coordinator_number))
})

test("each table elects, projects, and replaces its coordinator atomically", async t => {
  const db = await createFixture(t)

  const opened = await coordinate(db, { participant: 1, operation: "open" })
  assert.equal(opened.status, "voting")
  assert.equal(opened.member_count, 3)
  assert.equal(opened.votes_cast, 0)
  assert.equal(opened.table_number, 1)

  await coordinate(db, { participant: 1, operation: "vote", candidate: 2 })
  await coordinate(db, { participant: 2, operation: "vote", candidate: 2 })
  const elected = await coordinate(db, { participant: 3, operation: "vote", candidate: 1 })
  assert.equal(elected.status, "elected")
  assert.equal(elected.coordinator_number, 2)
  assert.equal(elected.votes_cast, 3)
  assert.equal(elected.my_vote, 1)

  await expectDbError(
    coordinate(db, {
      participant: 1,
      operation: "publish",
      content: { kind: "activity", title: "غير مسموح", body: "", activity_id: "blocked" },
    }),
    /Only the elected table coordinator/i,
  )

  const projected = await coordinate(db, {
    participant: 2,
    operation: "publish",
    content: {
      kind: "question",
      title: "ما أكثر شيء فاجأك اليوم؟",
      body: "كل شخص يجيب باختصار",
      activity_id: "discussion-questions",
    },
  })
  assert.equal(projected.content_version, 1)
  assert.deepEqual(projected.active_content, {
    kind: "question",
    title: "ما أكثر شيء فاجأك اليوم؟",
    body: "كل شخص يجيب باختصار",
    activity_id: "discussion-questions",
  })
  const followerView = await coordinate(db, { participant: 3, operation: "status" })
  assert.deepEqual(followerView.active_content, projected.active_content)
  assert.equal(followerView.my_vote, 1)

  const revolt = await coordinate(db, { participant: 3, operation: "revolt" })
  assert.equal(revolt.status, "voting")
  assert.equal(revolt.kind, "revolt")
  assert.equal(revolt.election_version, 2)
  assert.equal(revolt.coordinator_number, 2)
  await expectDbError(
    coordinate(db, { participant: 1, operation: "vote", candidate: 2 }),
    /Choose a different coordinator/i,
  )

  await coordinate(db, { participant: 1, operation: "vote", candidate: 1 })
  await coordinate(db, { participant: 2, operation: "vote", candidate: 1 })
  const replacement = await coordinate(db, { participant: 3, operation: "vote", candidate: 3 })
  assert.equal(replacement.status, "elected")
  assert.equal(replacement.coordinator_number, 1)
  assert.equal(replacement.previous_coordinator_number, 2)

  const otherTable = await coordinate(db, { participant: 4, operation: "status" })
  assert.equal(otherTable.status, "idle")
  assert.equal(otherTable.table_number, 2)
  assert.equal(otherTable.member_count, 2)

  await coordinate(db, { participant: 4, operation: "open" })
  await db.exec(`update public.event3_group_coordination
    set election_deadline = clock_timestamp() - interval '1 second'
    where event_id = ${EVENT_ID} and round = 1 and table_number = 2 and session_key = 'live'`)
  const timedOut = await coordinate(db, { participant: 5, operation: "status" })
  assert.equal(timedOut.status, "elected")
  assert.equal(timedOut.coordinator_number, 4)

  await db.exec(`update public.event_state
    set test_mode_active = true,
        test_mode_snapshot = '{"started_at":"${STARTED_AT}"}'::jsonb
    where match_id = '${EVENT3_MATCH_ID}'::uuid`)
  const isolatedTestState = await coordinate(db, {
    participant: 1,
    operation: "status",
    testMode: true,
    startedAt: STARTED_AT,
  })
  assert.equal(isolatedTestState.status, "idle")
  await expectDbError(
    coordinate(db, {
      participant: 1,
      operation: "status",
      testMode: true,
      startedAt: "2026-09-06T00:01:00.000Z",
    }),
    /test session changed/i,
  )
})

test("participant API and Event3 UI expose the full election and synchronized projector contract", async () => {
  const [api, event3, groups, prompts] = await Promise.all([
    readFile(new URL("../../api/participant.mjs", import.meta.url), "utf8"),
    readFile(new URL("../../app/routes/event3.tsx", import.meta.url), "utf8"),
    readFile(new URL("../../app/routes/groups.tsx", import.meta.url), "utf8"),
    readFile(new URL("../../app/components/PromptTopicsModal.tsx", import.meta.url), "utf8"),
  ])

  for (const action of [
    "e3-get-group-coordination",
    "e3-open-group-election",
    "e3-cast-group-coordinator-vote",
    "e3-start-group-reelection",
    "e3-finalize-group-election",
    "e3-direct-group-coordinator",
    "e3-random-group-coordinator",
    "e3-publish-group-content",
    "e3-clear-group-content",
  ]) {
    assert.match(api, new RegExp(`"${action}"`))
    assert.match(event3, new RegExp(`"${action}"`))
  }
  assert.match(api, /activeEvent3Phase !== `round\$\{requestedRound\}`/)
  assert.match(api, /p_expected_test_mode: requestTestMode/)
  assert.match(api, /p_expected_started_at:/)
  assert.match(event3, /function GroupElectionOverlay/)
  assert.match(event3, /function GroupProjectorOverlay/)
  assert.match(event3, /فك المزامنة والتصفّح بحرية/)
  assert.match(event3, /العودة لبث/)
  assert.match(event3, /انقلاب/)
  assert.match(event3, /يعطي كل شخص فرصته للكلام/)
  assert.match(event3, /تخطّي المؤقت وحسم الأصوات/)
  assert.match(event3, /اختيار منسّق عشوائياً/)
  assert.match(event3, /تعيين .* مباشرة/)
  assert.match(groups, /onSharedContentChange/)
  assert.match(groups, /onRequestReelection/)
  assert.match(prompts, /onQuestionChange\?\.\(currentQuestion/)
})
