import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"
import { PGlite } from "@electric-sql/pglite"

const EVENT3_MATCH_ID = "00000000-0000-0000-0000-000000000003"
const EVENT_ID = 26
const MIGRATION_URL = new URL(
  "../../supabase/migrations/20260902050000_harden_event3_group_seat_swaps.sql",
  import.meta.url,
)

async function expectDbError(promise, pattern) {
  await assert.rejects(promise, error => {
    assert.match(String(error?.message || error), pattern)
    return true
  })
}

test("participant seat controls call the active-session-CAS v2 swap", async () => {
  const [adminApi, adminUi, migration] = await Promise.all([
    readFile(new URL("../../api/admin/index.mjs", import.meta.url), "utf8"),
    readFile(new URL("../../app/routes/admin3.tsx", import.meta.url), "utf8"),
    readFile(MIGRATION_URL, "utf8"),
  ])
  const swapApi = adminApi.slice(
    adminApi.indexOf('if (action === "e3-swap-seating")'),
    adminApi.indexOf('// e3-clear-rankings'),
  )
  const doSwapUi = adminUi.slice(
    adminUi.indexOf("const doSwap ="),
    adminUi.indexOf("const doMove ="),
  )
  const seatingTabsUi = adminUi.slice(
    adminUi.indexOf("{/* TAB: SEATING MAP"),
    adminUi.indexOf("{choiceOnly ? (", adminUi.indexOf("{/* TAB: SEATING MAP")),
  )

  assert.match(swapApi, /select\("current_event_id,test_mode_active,test_mode_snapshot"\)/)
  assert.match(swapApi, /\.maybeSingle\(\)/)
  assert.match(swapApi, /rpc\("swap_event3_group_seats_v2"/)
  assert.doesNotMatch(swapApi, /rpc\("swap_event3_group_seats",/)
  assert.match(swapApi, /p_expected_test_mode: seatingSwapState\.test_mode_active === true/)
  assert.match(swapApi, /p_expected_started_at: seatingSwapState\.test_mode_snapshot\?\.started_at \|\| null/)
  assert.match(swapApi, /\["55000", "P0001"\]\.includes\(error\.code\) \? 409/)
  assert.match(swapApi, /data\?\.event_format === "choice_only_three_groups"/)
  assert.match(doSwapUi, /if \(\[20, 30, 40\]\.includes\(mapRound\)\)/)
  assert.doesNotMatch(doSwapUi, /choiceOnly && \[20, 30, 40\]/)
  assert.match(seatingTabsUi, /setMapRound\(20\); setSwapA\(null\); setMoveA\(null\); setEditingTableCard\(null\)/)
  assert.match(seatingTabsUi, /setMapRound\(30\); setSwapA\(null\); setMoveA\(null\); setEditingTableCard\(null\)/)

  assert.match(migration, /drop function public\.swap_event3_group_seats\(uuid, integer, integer, integer\)/)
  assert.match(migration, /create or replace function public\.swap_event3_group_seats_v2/)
  assert.match(migration, /p_expected_test_mode boolean[\s\S]*p_expected_started_at text/)
  assert.match(migration, /:event3-runtime/)
  assert.doesNotMatch(migration, /:group-seats/)
  assert.match(migration, /from public\.event_state state[\s\S]*for update/)
  assert.match(migration, /current_event_id is distinct from p_event_id/)
  assert.match(migration, /test_mode_snapshot ->> 'started_at'/)
  assert.match(migration, /v_state\.phase is distinct from 'setup'/)
  assert.match(migration, /v_rounds := array\[1, 2, 3\]::smallint\[\]/)
  assert.match(migration, /v_rounds := array\[1, 2\]::smallint\[\]/)
  assert.match(migration, /lock table public\.session_assignments in share row exclusive mode/)
  assert.match(migration, /Both participants must have an assignment in every choice-only group round/)
  assert.match(migration, /v_updated <> 6/)
  assert.match(migration, /security invoker/)
  assert.match(migration, /grant execute[\s\S]*to service_role/)
})

test("v2 swaps the format-specific group rounds and rejects stale event sessions atomically", async t => {
  const db = new PGlite()
  t.after(() => db.close())
  await db.exec(`
    create role anon;
    create role authenticated;
    create role service_role;

    create table event_state (
      match_id uuid primary key,
      phase text,
      current_event_id integer,
      test_mode_active boolean default false,
      test_mode_snapshot jsonb
    );
    create table event3_event_settings (
      match_id uuid not null,
      event_id integer not null,
      event_format text not null check (event_format in ('classic', 'choice_only_three_groups')),
      primary key (match_id, event_id)
    );
    create table session_assignments (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      round smallint not null,
      table_number integer not null,
      participant_id integer not null,
      unique (match_id, event_id, round, participant_id)
    );

    create function swap_event3_group_seats(
      uuid, integer, integer, integer
    ) returns jsonb language sql as $legacy$ select '{}'::jsonb $legacy$;
  `)
  await db.exec(await readFile(MIGRATION_URL, "utf8"))

  const signatures = await db.query(`select
    to_regprocedure('public.swap_event3_group_seats(uuid,integer,integer,integer)')::text as legacy,
    to_regprocedure('public.swap_event3_group_seats_v2(uuid,integer,integer,integer,boolean,text)')::text as current,
    has_function_privilege(
      'anon',
      'public.swap_event3_group_seats_v2(uuid,integer,integer,integer,boolean,text)',
      'execute'
    ) as anon_can_swap,
    has_function_privilege(
      'service_role',
      'public.swap_event3_group_seats_v2(uuid,integer,integer,integer,boolean,text)',
      'execute'
    ) as service_can_swap`)
  assert.deepEqual(signatures.rows, [{
    legacy: null,
    current: "swap_event3_group_seats_v2(uuid,integer,integer,integer,boolean,text)",
    anon_can_swap: false,
    service_can_swap: true,
  }])

  await db.query(`insert into event_state(
    match_id,phase,current_event_id,test_mode_active,test_mode_snapshot
  ) values ($1,'setup',$2,false,null)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into event3_event_settings(match_id,event_id,event_format)
    values ($1,$2,'choice_only_three_groups')`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into session_assignments(match_id,event_id,round,table_number,participant_id)
    select $1,$2,round_number,table_number,participant_id
    from (values
      (1::smallint,1,1),(1::smallint,2,2),
      (2::smallint,3,1),(2::smallint,4,2),
      (3::smallint,5,1),(3::smallint,6,2),
      (30::smallint,7,1),(30::smallint,8,2)
    ) rows(round_number,table_number,participant_id)`, [EVENT3_MATCH_ID, EVENT_ID])

  const choiceSwap = await db.query(`select swap_event3_group_seats_v2(
    $1,$2,1,2,false,null
  ) as result`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.equal(choiceSwap.rows[0].result.event_format, "choice_only_three_groups")
  assert.equal(choiceSwap.rows[0].result.updated_assignments, 6)
  assert.deepEqual(choiceSwap.rows[0].result.rounds, [1, 2, 3])
  const choiceTables = await db.query(`select round,participant_id,table_number
    from session_assignments order by round,participant_id`)
  assert.deepEqual(choiceTables.rows, [
    { round: 1, participant_id: 1, table_number: 2 },
    { round: 1, participant_id: 2, table_number: 1 },
    { round: 2, participant_id: 1, table_number: 4 },
    { round: 2, participant_id: 2, table_number: 3 },
    { round: 3, participant_id: 1, table_number: 6 },
    { round: 3, participant_id: 2, table_number: 5 },
    { round: 30, participant_id: 1, table_number: 7 },
    { round: 30, participant_id: 2, table_number: 8 },
  ])

  await db.query(`update event_state set test_mode_active=true,
    test_mode_snapshot='{"started_at":"session-b"}'::jsonb where match_id=$1`, [EVENT3_MATCH_ID])
  await expectDbError(db.query(`select swap_event3_group_seats_v2(
    $1,$2,1,2,false,null
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /live\/test session changed/i)
  await expectDbError(db.query(`select swap_event3_group_seats_v2(
    $1,$2,1,2,true,'session-a'
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /live\/test session changed/i)
  const afterStaleSession = await db.query(`select round,participant_id,table_number
    from session_assignments order by round,participant_id`)
  assert.deepEqual(afterStaleSession.rows, choiceTables.rows)

  const exactTestSwap = await db.query(`select swap_event3_group_seats_v2(
    $1,$2,1,2,true,'session-b'
  ) as result`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.equal(exactTestSwap.rows[0].result.updated_assignments, 6)

  await db.query(`update event_state set phase='phase1' where match_id=$1`, [EVENT3_MATCH_ID])
  await expectDbError(db.query(`select swap_event3_group_seats_v2(
    $1,$2,1,2,true,'session-b'
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /only be swapped during setup/i)

  await db.query(`update event3_event_settings set event_format='classic'
    where match_id=$1 and event_id=$2`, [EVENT3_MATCH_ID, EVENT_ID])
  const classicSwap = await db.query(`select swap_event3_group_seats_v2(
    $1,$2,1,2,true,'session-b'
  ) as result`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.equal(classicSwap.rows[0].result.event_format, "classic")
  assert.equal(classicSwap.rows[0].result.updated_assignments, 4)
  assert.deepEqual(classicSwap.rows[0].result.rounds, [1, 2])
  const classicTables = await db.query(`select round,participant_id,table_number
    from session_assignments order by round,participant_id`)
  assert.deepEqual(classicTables.rows, [
    { round: 1, participant_id: 1, table_number: 2 },
    { round: 1, participant_id: 2, table_number: 1 },
    { round: 2, participant_id: 1, table_number: 4 },
    { round: 2, participant_id: 2, table_number: 3 },
    { round: 3, participant_id: 1, table_number: 5 },
    { round: 3, participant_id: 2, table_number: 6 },
    { round: 30, participant_id: 1, table_number: 7 },
    { round: 30, participant_id: 2, table_number: 8 },
  ])

  await expectDbError(db.query(`select swap_event3_group_seats_v2(
    $1,$2 + 1,1,2,true,'session-b'
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /active current event/i)
  const afterStaleEvent = await db.query(`select round,participant_id,table_number
    from session_assignments order by round,participant_id`)
  assert.deepEqual(afterStaleEvent.rows, classicTables.rows)

  await db.query(`update event3_event_settings set event_format='choice_only_three_groups'
    where match_id=$1 and event_id=$2`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`update event_state set phase='setup' where match_id=$1`, [EVENT3_MATCH_ID])
  await db.query(`delete from session_assignments where match_id=$1 and event_id=$2 and round=3`,
    [EVENT3_MATCH_ID, EVENT_ID])
  const bothMissingBefore = await db.query(`select round,participant_id,table_number
    from session_assignments order by round,participant_id`)
  await expectDbError(db.query(`select swap_event3_group_seats_v2(
    $1,$2,1,2,true,'session-b'
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /every choice-only group round/i)
  const afterBothMissing = await db.query(`select round,participant_id,table_number
    from session_assignments order by round,participant_id`)
  assert.deepEqual(afterBothMissing.rows, bothMissingBefore.rows)

  await db.query(`insert into session_assignments(match_id,event_id,round,table_number,participant_id)
    values ($1,$2,3,5,1)`, [EVENT3_MATCH_ID, EVENT_ID])
  const oneMissingBefore = await db.query(`select round,participant_id,table_number
    from session_assignments order by round,participant_id`)
  await expectDbError(db.query(`select swap_event3_group_seats_v2(
    $1,$2,1,2,true,'session-b'
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /every choice-only group round/i)
  const afterOneMissing = await db.query(`select round,participant_id,table_number
    from session_assignments order by round,participant_id`)
  assert.deepEqual(afterOneMissing.rows, oneMissingBefore.rows)
})
