import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"
import { PGlite } from "@electric-sql/pglite"

const EVENT3_MATCH_ID = "00000000-0000-0000-0000-000000000003"
const STATIC_MATCH_ID = "00000000-0000-0000-0000-000000000000"
const EVENT_ID = 26
const TEST_SESSION = "2026-09-06T11:45:00.000Z"
const migrationUrl = new URL(
  "../../supabase/migrations/20260906113631_harden_event3_runtime_reset.sql",
  import.meta.url,
)

async function fixture(t) {
  const db = new PGlite()
  t.after(() => db.close())
  await db.exec(`
    create role anon;
    create role authenticated;
    create role service_role;

    create table event_state (
      match_id uuid primary key,
      current_event_id integer,
      phase text,
      announcement text,
      announcement_type text,
      announcement_time timestamptz,
      emergency_paused boolean default false,
      pause_time timestamptz,
      current_round integer,
      global_timer_active boolean,
      global_timer_start_time timestamptz,
      global_timer_duration integer,
      global_timer_round integer,
      results_visible boolean,
      groups_locked boolean,
      phase2_score_revealed boolean,
      phase3_score_revealed boolean,
      test_mode_active boolean default false,
      test_mode_snapshot jsonb,
      cohost_locked boolean default false,
      cohost_lock_updated_at timestamptz,
      cohost_lock_updated_by text,
      event3_participant_access_locked boolean default false
    );
    create table event3_group_coordination (
      match_id uuid, event_id integer, session_key text, round smallint, table_number integer,
      primary key (match_id, event_id, session_key, round, table_number)
    );
    create table event3_group_coordinator_votes (
      match_id uuid, event_id integer, session_key text, round smallint, table_number integer,
      election_version integer, voter_number integer, candidate_number integer,
      primary key (match_id, event_id, session_key, round, table_number, election_version, voter_number),
      foreign key (match_id, event_id, session_key, round, table_number)
        references event3_group_coordination(match_id, event_id, session_key, round, table_number)
        on delete cascade
    );
    create table event3_choice_seating_reports (
      id bigint generated by default as identity primary key,
      match_id uuid, event_id integer, is_test_mode boolean, session_key text
    );
    create table event3_cohost_notes (
      id bigint generated by default as identity primary key,
      match_id uuid, event_id integer, test_mode boolean, test_session_key text
    );
    create table event3_group_member_feedback (
      id bigint generated by default as identity primary key,
      match_id uuid, event_id integer, is_test_mode boolean
    );
    create table event3_group_reflections (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table event3_participant_notes (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table event3_mood_checks (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table event3_notifications (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table event3_ai_welcome_messages (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table event3_test_match_results (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table organizer_requests (id bigint generated by default as identity primary key, event_id integer);
    create table event_attendance (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table participant_rankings (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table event3_ranking_drafts (
      id bigint generated by default as identity primary key,
      match_id uuid, event_id integer, session_key text
    );
    create table session_assignments (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table event3_matches (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table event3_exclusions (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
    create table event3_participants (id bigint generated by default as identity primary key, match_id uuid, event_id integer);

    create table event3_event_settings (match_id uuid, event_id integer, event_format text);
    create table event3_cohost_agreements (id bigint generated by default as identity primary key, agreement_hash text);
    create table event3_test_mode_snapshots (match_id uuid, event_id integer, snapshot jsonb);
    create table locked_matches (id bigint generated by default as identity primary key, match_id uuid, event_id integer);
  `)
  await db.exec(await readFile(migrationUrl, "utf8"))
  return db
}

async function scalar(db, sql) {
  const result = await db.query(sql)
  return Number(Object.values(result.rows[0])[0])
}

async function seedState(db, testMode = false) {
  await db.exec(`
    insert into event_state(
      match_id, current_event_id, phase, announcement, announcement_type,
      announcement_time, emergency_paused, pause_time, current_round,
      global_timer_active, global_timer_start_time, global_timer_duration,
      global_timer_round, results_visible, groups_locked,
      phase2_score_revealed, phase3_score_revealed, test_mode_active,
      test_mode_snapshot, cohost_locked, cohost_lock_updated_at,
      cohost_lock_updated_by, event3_participant_access_locked
    ) values (
      '${EVENT3_MATCH_ID}', ${EVENT_ID}, 'round3', 'notice', 'warning', now(),
      true, now(), 3, true, now(), 180, 3, true, true, true, true,
      ${testMode}, ${testMode ? `'${JSON.stringify({ started_at: TEST_SESSION })}'::jsonb` : "null"},
      true, now(), 'admin3', true
    );
  `)
}

async function seedRuntime(db, { testMode = false } = {}) {
  const runtimeSession = testMode ? TEST_SESSION : "live"
  const coordinationSession = testMode ? `test:${TEST_SESSION}` : "live"
  await db.exec(`
    insert into event3_group_coordination values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, '${coordinationSession}', 1, 1);
    insert into event3_group_coordinator_votes values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, '${coordinationSession}', 1, 1, 1, 1, 2);
    insert into event3_choice_seating_reports(match_id,event_id,is_test_mode,session_key)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, ${testMode}, '${runtimeSession}');
    insert into event3_cohost_notes(match_id,event_id,test_mode,test_session_key)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, ${testMode}, '${testMode ? runtimeSession : ""}');
    insert into event3_group_member_feedback(match_id,event_id,is_test_mode)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, ${testMode});
    insert into event3_group_reflections(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    insert into event3_participant_notes(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    insert into event3_mood_checks(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    insert into event3_notifications(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    insert into event3_ai_welcome_messages(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    insert into organizer_requests(event_id) values (${EVENT_ID});
    insert into event_attendance(match_id,event_id) values ('${STATIC_MATCH_ID}', ${EVENT_ID});
    insert into participant_rankings(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    insert into event3_ranking_drafts(match_id,event_id,session_key) values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, '${runtimeSession}');
    insert into session_assignments(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    insert into event3_matches(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    insert into event3_exclusions(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    insert into event3_participants(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    ${testMode ? `insert into event3_test_match_results(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});` : ""}
  `)
}

test("live reset removes every user-visible runtime artifact and preserves durable inputs", async t => {
  const db = await fixture(t)
  await seedState(db)
  await seedRuntime(db)
  await db.exec(`
    insert into event3_group_coordination values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, 'test:stale', 1, 1);
    insert into event3_choice_seating_reports(match_id,event_id,is_test_mode,session_key)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, true, 'stale');
    insert into event3_cohost_notes(match_id,event_id,test_mode,test_session_key)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, true, 'stale');
    insert into event3_group_member_feedback(match_id,event_id,is_test_mode)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, true);
    insert into event3_ranking_drafts(match_id,event_id,session_key)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, 'stale');
    insert into event3_test_match_results(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID});
    insert into event3_test_mode_snapshots values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, '{}');
    insert into event3_event_settings values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, 'choice_only_three_groups');
    insert into event3_cohost_agreements(agreement_hash) values ('keep-me');
    insert into locked_matches(match_id,event_id) values ('${STATIC_MATCH_ID}', ${EVENT_ID});

    insert into event3_participants(match_id,event_id) values ('${EVENT3_MATCH_ID}', ${EVENT_ID + 1});
    insert into organizer_requests(event_id) values (${EVENT_ID + 1});
    insert into event_attendance(match_id,event_id) values ('${STATIC_MATCH_ID}', ${EVENT_ID + 1});
  `)

  const reset = await db.query(`
    select reset_event3_runtime_v2('${EVENT3_MATCH_ID}', ${EVENT_ID}, false, null) as result
  `)
  assert.equal(reset.rows[0].result.success, true)
  assert.equal(Number(reset.rows[0].result.runtime_generation), 2)
  assert.equal(reset.rows[0].result.cache_preserved, true)

  for (const table of [
    "event3_group_reflections", "event3_participant_notes", "event3_mood_checks",
    "event3_notifications", "event3_ai_welcome_messages", "participant_rankings",
    "session_assignments", "event3_matches", "event3_exclusions", "event3_participants",
  ]) {
    assert.equal(await scalar(db, `select count(*) from ${table} where match_id='${EVENT3_MATCH_ID}' and event_id=${EVENT_ID}`), 0, table)
  }
  assert.equal(await scalar(db, `select count(*) from organizer_requests where event_id=${EVENT_ID}`), 0)
  assert.equal(await scalar(db, `select count(*) from event_attendance where match_id='${STATIC_MATCH_ID}' and event_id=${EVENT_ID}`), 0)
  assert.equal(await scalar(db, `select count(*) from event3_group_coordination where session_key='live'`), 0)
  assert.equal(await scalar(db, `select count(*) from event3_group_coordinator_votes where session_key='live'`), 0)
  assert.equal(await scalar(db, `select count(*) from event3_choice_seating_reports where is_test_mode=false`), 0)
  assert.equal(await scalar(db, `select count(*) from event3_cohost_notes where test_mode=false`), 0)
  assert.equal(await scalar(db, `select count(*) from event3_group_member_feedback where is_test_mode=false`), 0)
  assert.equal(await scalar(db, `select count(*) from event3_ranking_drafts where session_key='live'`), 0)

  assert.equal(await scalar(db, `select count(*) from event3_group_coordination where session_key='test:stale'`), 1)
  assert.equal(await scalar(db, `select count(*) from event3_choice_seating_reports where is_test_mode=true`), 1)
  assert.equal(await scalar(db, `select count(*) from event3_cohost_notes where test_mode=true`), 1)
  assert.equal(await scalar(db, `select count(*) from event3_group_member_feedback where is_test_mode=true`), 1)
  assert.equal(await scalar(db, `select count(*) from event3_ranking_drafts where session_key='stale'`), 1)
  assert.equal(await scalar(db, `select count(*) from event3_test_match_results where event_id=${EVENT_ID}`), 1)
  assert.equal(await scalar(db, `select count(*) from event3_test_mode_snapshots where event_id=${EVENT_ID}`), 1)
  assert.equal(await scalar(db, `select count(*) from event3_event_settings where event_id=${EVENT_ID}`), 1)
  assert.equal(await scalar(db, "select count(*) from event3_cohost_agreements"), 1)
  assert.equal(await scalar(db, `select count(*) from locked_matches where event_id=${EVENT_ID}`), 1)
  assert.equal(await scalar(db, `select count(*) from event3_participants where event_id=${EVENT_ID + 1}`), 1)
  assert.equal(await scalar(db, `select count(*) from organizer_requests where event_id=${EVENT_ID + 1}`), 1)
  assert.equal(await scalar(db, `select count(*) from event_attendance where event_id=${EVENT_ID + 1}`), 1)

  const state = (await db.query(`select * from event_state where match_id='${EVENT3_MATCH_ID}'`)).rows[0]
  assert.equal(state.phase, "setup")
  assert.equal(state.current_round, 1)
  assert.equal(state.announcement, null)
  assert.equal(state.emergency_paused, false)
  assert.equal(state.global_timer_active, false)
  assert.equal(state.results_visible, false)
  assert.equal(state.groups_locked, false)
  assert.equal(state.cohost_locked, false)
  assert.equal(state.event3_participant_access_locked, false)
  assert.equal(state.test_mode_active, false)
  assert.equal(state.test_mode_snapshot, null)
})

test("test reset removes only the active test-session residue and keeps its restore snapshot", async t => {
  const db = await fixture(t)
  await seedState(db, true)
  await seedRuntime(db, { testMode: true })
  await db.exec(`
    insert into event3_group_coordination values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, 'live', 1, 1);
    insert into event3_choice_seating_reports(match_id,event_id,is_test_mode,session_key)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, false, 'live');
    insert into event3_cohost_notes(match_id,event_id,test_mode,test_session_key)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, false, '');
    insert into event3_group_member_feedback(match_id,event_id,is_test_mode)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, false);
    insert into event3_ranking_drafts(match_id,event_id,session_key)
      values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, 'live');
    insert into event3_test_mode_snapshots values ('${EVENT3_MATCH_ID}', ${EVENT_ID}, '{"restore":"live"}');
  `)

  await db.query(`
    select reset_event3_runtime_v2('${EVENT3_MATCH_ID}', ${EVENT_ID}, true, '${TEST_SESSION}')
  `)

  assert.equal(await scalar(db, `select count(*) from event3_group_coordination where session_key='test:${TEST_SESSION}'`), 0)
  assert.equal(await scalar(db, "select count(*) from event3_group_coordination where session_key='live'"), 1)
  assert.equal(await scalar(db, "select count(*) from event3_choice_seating_reports where is_test_mode=true"), 0)
  assert.equal(await scalar(db, "select count(*) from event3_choice_seating_reports where is_test_mode=false"), 1)
  assert.equal(await scalar(db, "select count(*) from event3_cohost_notes where test_mode=true"), 0)
  assert.equal(await scalar(db, "select count(*) from event3_cohost_notes where test_mode=false"), 1)
  assert.equal(await scalar(db, "select count(*) from event3_group_member_feedback where is_test_mode=true"), 0)
  assert.equal(await scalar(db, "select count(*) from event3_group_member_feedback where is_test_mode=false"), 1)
  assert.equal(await scalar(db, `select count(*) from event3_ranking_drafts where session_key='${TEST_SESSION}'`), 0)
  assert.equal(await scalar(db, "select count(*) from event3_ranking_drafts where session_key='live'"), 1)
  assert.equal(await scalar(db, `select count(*) from event3_test_match_results where event_id=${EVENT_ID}`), 0)
  assert.equal(await scalar(db, `select count(*) from event3_test_mode_snapshots where event_id=${EVENT_ID}`), 1)

  const state = (await db.query(`select * from event_state where match_id='${EVENT3_MATCH_ID}'`)).rows[0]
  assert.equal(state.phase, "setup")
  assert.equal(state.test_mode_active, true)
  assert.equal(state.test_mode_snapshot.started_at, TEST_SESSION)
  assert.equal(Number(state.event3_runtime_generation), 2)
})

test("reset API requires the transaction and live browser artifacts are generation-scoped", async () => {
  const [admin, participant, route] = await Promise.all([
    readFile(new URL("../../api/admin/index.mjs", import.meta.url), "utf8"),
    readFile(new URL("../../api/participant.mjs", import.meta.url), "utf8"),
    readFile(new URL("../../app/routes/event3.tsx", import.meta.url), "utf8"),
  ])
  const resetBlock = admin.slice(admin.indexOf('if (action === "e3-reset-event")'), admin.indexOf('// e3-get-attendance'))
  assert.match(resetBlock, /rpc\("reset_event3_runtime_v2"/)
  assert.doesNotMatch(resetBlock, /Promise\.all/)
  assert.doesNotMatch(resetBlock, /Classic-only rolling-deployment fallback/)
  assert.match(participant, /event3_runtime_generation/)
  assert.match(participant, /`live:\$\{currentEventId\}:\$\{Number\(e3EventState\?\.event3_runtime_generation\) \|\| 1\}`/)
  assert.match(route, /event3_runtime_session_key[\s\S]*e3_arrived_/)
})
