import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"
import { PGlite } from "@electric-sql/pglite"

const EVENT3_MATCH_ID = "00000000-0000-0000-0000-000000000003"
const EVENT_ID = 26
const MIGRATION_URL = new URL(
  "../../supabase/migrations/20260902043000_harden_event3_table_number_swaps.sql",
  import.meta.url,
)

async function expectDbError(promise, pattern) {
  await assert.rejects(promise, error => {
    assert.match(String(error?.message || error), pattern)
    return true
  })
}

test("table controls call the format-aware, session-CAS v2 swap", async () => {
  const [adminApi, adminUi, migration] = await Promise.all([
    readFile(new URL("../../api/admin/index.mjs", import.meta.url), "utf8"),
    readFile(new URL("../../app/routes/admin3.tsx", import.meta.url), "utf8"),
    readFile(MIGRATION_URL, "utf8"),
  ])

  const moveApi = adminApi.slice(
    adminApi.indexOf('if (action === "e3-move-table")'),
    adminApi.indexOf('// e3-swap-table-numbers'),
  )
  const choiceTableUi = adminUi.slice(
    adminUi.indexOf('1:1 Pairs View'),
    adminUi.indexOf('Object.keys(seating?.[mapRound]'),
  )

  assert.match(adminApi, /rpc\("swap_event3_table_numbers_v2"/)
  assert.match(adminApi, /getTableSwapRounds\(round, \{ choiceOnly: choiceOnlyTableSwap \}\)/)
  assert.match(adminApi, /p_expected_test_mode: tableSwapState\.test_mode_active === true/)
  assert.match(adminApi, /p_expected_started_at: tableSwapState\.test_mode_snapshot\?\.started_at \|\| null/)
  assert.match(adminApi, /Round must be 1, 2, 3, 20, or 30/)
  assert.match(adminApi, /data\?\.event_format === "choice_only_three_groups" \? "group rounds 1, 2, and 3" : "group rounds 1 and 2"/)
  assert.match(moveApi, /if \(!\[1, 2, 3\]\.includes\(assignmentRound\)\)/)
  assert.match(moveApi, /One-to-one rounds must use the atomic table swap/)
  assert.match(choiceTableUi, /renameTable\(20, pair\.table, targetTable\)/)
  assert.doesNotMatch(choiceTableUi, /api\("e3-move-table"/)

  assert.match(migration, /drop function public\.swap_event3_table_numbers_v2\(uuid, integer, smallint\[\], integer, integer\)/)
  assert.match(migration, /create or replace function public\.swap_event3_table_numbers_v2/)
  assert.match(migration, /p_expected_test_mode boolean[\s\S]*p_expected_started_at text/)
  assert.match(migration, /:event3-runtime/)
  assert.doesNotMatch(migration, /:tables/)
  assert.match(migration, /current_event_id is distinct from p_event_id/)
  assert.match(migration, /test_mode_snapshot ->> 'started_at'/)
  assert.match(migration, /choice_only_three_groups[\s\S]*array\[1, 2, 3\]::smallint\[\]/)
  assert.doesNotMatch(migration, /array\[40\]::smallint\[\]/)
  assert.match(migration, /update public\.session_assignments/)
  assert.match(migration, /update public\.event3_test_match_results/)
  assert.match(migration, /security invoker/)
  assert.match(migration, /grant execute[\s\S]*to service_role/)
})

test("v2 migration swaps choice round 3, preserves classic groups, and rejects stale sessions", async t => {
  const db = new PGlite()
  t.after(() => db.close())
  await db.exec(`
    create role anon;
    create role authenticated;
    create role service_role;

    create table event_state (
      match_id uuid primary key,
      current_event_id integer,
      test_mode_active boolean default false,
      test_mode_snapshot jsonb
    );
    create table event3_event_settings (
      match_id uuid not null,
      event_id integer not null,
      event_format text not null check (event_format in ('classic', 'choice_only_three_groups')),
      primary key (match_id, event_id)
    );
    create table session_assignments (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      round smallint not null,
      table_number integer not null,
      participant_id integer not null,
      unique (match_id, event_id, round, participant_id)
    );
    create table event3_test_match_results (
      id bigint generated by default as identity primary key,
      match_id uuid not null,
      event_id integer not null,
      participant_a_number integer not null,
      participant_b_number integer not null,
      table_number integer
    );

    create function swap_event3_table_numbers_v2(
      uuid, integer, smallint[], integer, integer
    ) returns jsonb language sql as $legacy$ select '{}'::jsonb $legacy$;
  `)
  await db.exec(await readFile(MIGRATION_URL, "utf8"))

  const signatures = await db.query(`select
    to_regprocedure('public.swap_event3_table_numbers_v2(uuid,integer,smallint[],integer,integer)')::text as legacy,
    to_regprocedure('public.swap_event3_table_numbers_v2(uuid,integer,smallint[],integer,integer,boolean,text)')::text as current,
    has_function_privilege(
      'anon',
      'public.swap_event3_table_numbers_v2(uuid,integer,smallint[],integer,integer,boolean,text)',
      'execute'
    ) as anon_can_swap,
    has_function_privilege(
      'service_role',
      'public.swap_event3_table_numbers_v2(uuid,integer,smallint[],integer,integer,boolean,text)',
      'execute'
    ) as service_can_swap`)
  assert.deepEqual(signatures.rows, [{
    legacy: null,
    current: "swap_event3_table_numbers_v2(uuid,integer,smallint[],integer,integer,boolean,text)",
    anon_can_swap: false,
    service_can_swap: true,
  }])

  await db.query(`insert into event_state(match_id,current_event_id,test_mode_active,test_mode_snapshot)
    values ($1,$2,false,null)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into event3_event_settings(match_id,event_id,event_format)
    values ($1,$2,'choice_only_three_groups')`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into session_assignments(match_id,event_id,round,table_number,participant_id)
    select $1,$2,round_number,table_number,participant_id
    from (values
      (1::smallint,1,1),(1::smallint,2,2),
      (2::smallint,1,1),(2::smallint,2,2),
      (3::smallint,1,1),(3::smallint,2,2)
    ) rows(round_number,table_number,participant_id)`, [EVENT3_MATCH_ID, EVENT_ID])

  const choiceSwap = await db.query(`select swap_event3_table_numbers_v2(
    $1,$2,array[1,2,3]::smallint[],1,2,false,null
  ) as result`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.equal(choiceSwap.rows[0].result.updated_assignments, 6)
  assert.deepEqual(choiceSwap.rows[0].result.rounds, [1, 2, 3])
  const choiceTables = await db.query(`select round,participant_id,table_number
    from session_assignments order by round,participant_id`)
  assert.deepEqual(choiceTables.rows, [
    { round: 1, participant_id: 1, table_number: 2 },
    { round: 1, participant_id: 2, table_number: 1 },
    { round: 2, participant_id: 1, table_number: 2 },
    { round: 2, participant_id: 2, table_number: 1 },
    { round: 3, participant_id: 1, table_number: 2 },
    { round: 3, participant_id: 2, table_number: 1 },
  ])

  await expectDbError(db.query(`select swap_event3_table_numbers_v2(
    $1,$2,array[40]::smallint[],1,2,false,null
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /choice-only table swaps must target/i)
  await expectDbError(db.query(`select swap_event3_table_numbers_v2(
    $1,$2 + 1,array[1,2,3]::smallint[],1,2,false,null
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /active current event/i)

  await db.query(`update event3_event_settings set event_format='classic'
    where match_id=$1 and event_id=$2`, [EVENT3_MATCH_ID, EVENT_ID])
  await expectDbError(db.query(`select swap_event3_table_numbers_v2(
    $1,$2,array[1,2,3]::smallint[],1,2,false,null
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /classic table swaps must target/i)
  const classicSwap = await db.query(`select swap_event3_table_numbers_v2(
    $1,$2,array[1,2]::smallint[],1,2,false,null
  ) as result`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.equal(classicSwap.rows[0].result.updated_assignments, 4)
  const untouchedClassicRound3 = await db.query(`select participant_id,table_number
    from session_assignments where round=3 order by participant_id`)
  assert.deepEqual(untouchedClassicRound3.rows, [
    { participant_id: 1, table_number: 2 },
    { participant_id: 2, table_number: 1 },
  ])

  await db.query(`insert into session_assignments(match_id,event_id,round,table_number,participant_id)
    values ($1,$2,30,1,101),($1,$2,30,1,102),($1,$2,30,2,201),($1,$2,30,2,202)`,
  [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`insert into event3_test_match_results(
    match_id,event_id,participant_a_number,participant_b_number,table_number
  ) values ($1,$2,101,102,1)`, [EVENT3_MATCH_ID, EVENT_ID])
  await db.query(`update event_state set test_mode_active=true,
    test_mode_snapshot='{"started_at":"session-b"}'::jsonb where match_id=$1`, [EVENT3_MATCH_ID])

  await expectDbError(db.query(`select swap_event3_table_numbers_v2(
    $1,$2,array[30]::smallint[],1,2,false,null
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /live\/test session changed/i)
  await expectDbError(db.query(`select swap_event3_table_numbers_v2(
    $1,$2,array[30]::smallint[],1,2,true,'session-a'
  )`, [EVENT3_MATCH_ID, EVENT_ID]), /live\/test session changed/i)
  const assignmentsAfterStaleSession = await db.query(`select participant_id,table_number
    from session_assignments where round=30 order by participant_id`)
  assert.deepEqual(assignmentsAfterStaleSession.rows, [
    { participant_id: 101, table_number: 1 },
    { participant_id: 102, table_number: 1 },
    { participant_id: 201, table_number: 2 },
    { participant_id: 202, table_number: 2 },
  ])
  const resultAfterStaleSession = await db.query("select table_number from event3_test_match_results")
  assert.deepEqual(resultAfterStaleSession.rows, [{ table_number: 1 }])
  const testSwap = await db.query(`select swap_event3_table_numbers_v2(
    $1,$2,array[30]::smallint[],1,2,true,'session-b'
  ) as result`, [EVENT3_MATCH_ID, EVENT_ID])
  assert.equal(testSwap.rows[0].result.updated_assignments, 4)
  assert.equal(testSwap.rows[0].result.synced_test_results, 1)
  const syncedResult = await db.query("select table_number from event3_test_match_results")
  assert.deepEqual(syncedResult.rows, [{ table_number: 2 }])
})
