-- Optional post-feedback reflection on the people a participant met during
-- Event3 group rounds. This is intentionally separate from
-- participant_rankings, which drives the live matching algorithm.
CREATE TABLE IF NOT EXISTS public.event3_group_reflections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id uuid NOT NULL,
  event_id integer NOT NULL,
  ranker_number integer NOT NULL,
  ranked_numbers integer[] NOT NULL DEFAULT '{}'::integer[],
  organizer_note text,
  source_phase text NOT NULL DEFAULT 'phase2_feedback',
  submitted_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT event3_group_reflections_ranker_unique
    UNIQUE (match_id, event_id, ranker_number),
  CONSTRAINT event3_group_reflections_max_three
    CHECK (cardinality(ranked_numbers) BETWEEN 0 AND 3),
  CONSTRAINT event3_group_reflections_no_self_rank
    CHECK (NOT ranker_number = ANY(ranked_numbers)),
  CONSTRAINT event3_group_reflections_note_length
    CHECK (organizer_note IS NULL OR char_length(organizer_note) <= 300),
  CONSTRAINT event3_group_reflections_source_phase
    CHECK (source_phase IN ('phase2_feedback', 'phase3_feedback', 'event3'))
);

CREATE INDEX IF NOT EXISTS idx_event3_group_reflections_event
  ON public.event3_group_reflections(match_id, event_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_event3_group_reflections_ranked_numbers
  ON public.event3_group_reflections USING gin(ranked_numbers);

COMMENT ON TABLE public.event3_group_reflections IS
  'Optional top-three group-round reflections and private organizer notes; never used for live matching.';

ALTER TABLE public.event3_group_reflections ENABLE ROW LEVEL SECURITY;

-- Participant access is mediated by /api/participant, where the secure token
-- and actual group-table membership are validated. Keep the Data API closed.
REVOKE ALL ON TABLE public.event3_group_reflections FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.event3_group_reflections_id_seq FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.event3_group_reflections TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.event3_group_reflections_id_seq TO service_role;
