-- Standalone data model for The Room event operations.
-- These tables intentionally have no foreign keys, identifiers, or runtime
-- dependencies on BlindMatch, Event3, or the shared participant directory.

create table public.the_room_events (
  id uuid primary key default gen_random_uuid(),
  event_number bigint not null unique check (event_number > 0),
  name text not null default 'The Room' check (char_length(btrim(name)) between 1 and 120),
  starts_at timestamptz,
  venue text check (venue is null or char_length(venue) <= 240),
  status text not null default 'draft' check (status in ('draft', 'registration', 'ready', 'live', 'completed', 'cancelled')),
  minimum_attendees integer not null default 20 check (minimum_attendees >= 2 and minimum_attendees <= 500),
  table_count integer not null default 5 check (table_count >= 1 and table_count <= 50),
  round_count integer not null default 3 check (round_count >= 1 and round_count <= 20),
  ticket_price numeric(10, 2) not null default 0 check (ticket_price >= 0),
  currency text not null default 'SAR' check (currency ~ '^[A-Z]{3}$'),
  notes text check (notes is null or char_length(notes) <= 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.the_room_attendees (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.the_room_events(id) on delete cascade,
  attendee_number integer not null check (attendee_number > 0),
  full_name text not null check (char_length(btrim(full_name)) between 1 and 160),
  phone_e164 text check (phone_e164 is null or phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  gender text not null default 'unspecified' check (gender in ('male', 'female', 'nonbinary', 'unspecified')),
  attendance_status text not null default 'registered' check (attendance_status in ('registered', 'confirmed', 'waitlist', 'cancelled')),
  included_in_schedule boolean not null default true,
  checked_in boolean not null default false,
  payment_status text not null default 'pending' check (payment_status in ('pending', 'partial', 'paid', 'waived', 'refunded')),
  amount_due numeric(10, 2) not null default 0 check (amount_due >= 0),
  amount_paid numeric(10, 2) not null default 0 check (amount_paid >= 0),
  paid_at timestamptz,
  notes text check (notes is null or char_length(notes) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, attendee_number),
  unique (id, event_id)
);

create unique index the_room_attendees_event_phone_unique
  on public.the_room_attendees(event_id, phone_e164)
  where phone_e164 is not null;

create index the_room_attendees_event_status_idx
  on public.the_room_attendees(event_id, attendance_status, included_in_schedule);

create index the_room_attendees_event_payment_idx
  on public.the_room_attendees(event_id, payment_status);

create table public.the_room_payment_ledger (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.the_room_events(id) on delete cascade,
  attendee_id uuid not null,
  payment_status text not null check (payment_status in ('pending', 'partial', 'paid', 'waived', 'refunded')),
  amount_paid numeric(10, 2) not null default 0 check (amount_paid >= 0),
  note text check (note is null or char_length(note) <= 1000),
  recorded_by text not null default 'the-room-admin' check (char_length(recorded_by) between 1 and 120),
  recorded_at timestamptz not null default now(),
  foreign key (attendee_id, event_id)
    references public.the_room_attendees(id, event_id) on delete cascade
);

create index the_room_payment_ledger_event_attendee_idx
  on public.the_room_payment_ledger(event_id, attendee_id, recorded_at desc);

create table public.the_room_schedule_runs (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.the_room_events(id) on delete cascade,
  seed text not null check (char_length(seed) between 1 and 200),
  algorithm_version text not null check (char_length(algorithm_version) between 1 and 80),
  participant_count integer not null check (participant_count >= 2),
  table_count integer not null check (table_count >= 1),
  round_count integer not null check (round_count >= 1),
  metrics jsonb not null default '{}'::jsonb check (jsonb_typeof(metrics) = 'object'),
  is_active boolean not null default true,
  generated_at timestamptz not null default now(),
  unique (id, event_id)
);

create unique index the_room_one_active_schedule_per_event
  on public.the_room_schedule_runs(event_id)
  where is_active;

create table public.the_room_seats (
  id bigint generated by default as identity primary key,
  schedule_run_id uuid not null,
  event_id uuid not null,
  round_number integer not null check (round_number >= 1),
  table_number integer not null check (table_number >= 1),
  seat_number integer not null check (seat_number >= 1),
  attendee_id uuid not null,
  created_at timestamptz not null default now(),
  foreign key (schedule_run_id, event_id)
    references public.the_room_schedule_runs(id, event_id) on delete cascade,
  foreign key (attendee_id, event_id)
    references public.the_room_attendees(id, event_id) on delete restrict,
  unique (schedule_run_id, round_number, attendee_id),
  unique (schedule_run_id, round_number, table_number, seat_number)
);

create index the_room_seats_event_round_table_idx
  on public.the_room_seats(event_id, round_number, table_number, seat_number);

comment on table public.the_room_events is
  'Standalone numbered events for The Room; intentionally isolated from BlindMatch and Event3.';
comment on table public.the_room_attendees is
  'Event-scoped The Room guest roster, attendance state, and current payment state.';
comment on table public.the_room_payment_ledger is
  'Append-only history of The Room payment status changes.';
comment on table public.the_room_schedule_runs is
  'Versioned repeat-free table schedule generations for The Room.';
comment on table public.the_room_seats is
  'Round, table, and seat assignments for a The Room schedule generation.';

alter table public.the_room_events enable row level security;
alter table public.the_room_attendees enable row level security;
alter table public.the_room_payment_ledger enable row level security;
alter table public.the_room_schedule_runs enable row level security;
alter table public.the_room_seats enable row level security;

revoke all on table public.the_room_events from public, anon, authenticated;
revoke all on table public.the_room_attendees from public, anon, authenticated;
revoke all on table public.the_room_payment_ledger from public, anon, authenticated;
revoke all on table public.the_room_schedule_runs from public, anon, authenticated;
revoke all on table public.the_room_seats from public, anon, authenticated;
revoke all on sequence public.the_room_payment_ledger_id_seq from public, anon, authenticated;
revoke all on sequence public.the_room_seats_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.the_room_events to service_role;
grant select, insert, update, delete on table public.the_room_attendees to service_role;
grant select, insert, update, delete on table public.the_room_payment_ledger to service_role;
grant select, insert, update, delete on table public.the_room_schedule_runs to service_role;
grant select, insert, update, delete on table public.the_room_seats to service_role;
grant usage, select on sequence public.the_room_payment_ledger_id_seq to service_role;
grant usage, select on sequence public.the_room_seats_id_seq to service_role;

create or replace function public.record_the_room_payment(
  p_event_id uuid,
  p_attendee_id uuid,
  p_payment_status text,
  p_amount_paid numeric,
  p_note text default null
)
returns public.the_room_attendees
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_attendee public.the_room_attendees%rowtype;
begin
  if p_payment_status not in ('pending', 'partial', 'paid', 'waived', 'refunded') then
    raise exception 'Invalid The Room payment status';
  end if;
  if coalesce(p_amount_paid, 0) < 0 then
    raise exception 'Paid amount cannot be negative';
  end if;

  update public.the_room_attendees
  set payment_status = p_payment_status,
      amount_paid = coalesce(p_amount_paid, 0),
      paid_at = case
        when p_payment_status = 'paid' then coalesce(paid_at, pg_catalog.now())
        when p_payment_status in ('pending', 'refunded') then null
        else paid_at
      end,
      updated_at = pg_catalog.now()
  where id = p_attendee_id and event_id = p_event_id
  returning * into v_attendee;

  if not found then
    raise exception 'The Room attendee was not found in this event';
  end if;

  insert into public.the_room_payment_ledger (
    event_id, attendee_id, payment_status, amount_paid, note
  ) values (
    p_event_id,
    p_attendee_id,
    p_payment_status,
    coalesce(p_amount_paid, 0),
    nullif(pg_catalog.btrim(p_note), '')
  );

  return v_attendee;
end;
$$;

revoke execute on function public.record_the_room_payment(uuid, uuid, text, numeric, text)
  from public, anon, authenticated;
grant execute on function public.record_the_room_payment(uuid, uuid, text, numeric, text)
  to service_role;

create or replace function public.replace_the_room_schedule(
  p_event_id uuid,
  p_seed text,
  p_algorithm_version text,
  p_metrics jsonb,
  p_rows jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_event public.the_room_events%rowtype;
  v_run_id uuid := gen_random_uuid();
  v_participant_count integer;
  v_round_count integer;
  v_table_count integer;
  v_inserted integer;
begin
  if jsonb_typeof(coalesce(p_rows, '[]'::jsonb)) <> 'array' or jsonb_array_length(coalesce(p_rows, '[]'::jsonb)) = 0 then
    raise exception 'The Room schedule rows must be a non-empty array';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('the-room-schedule:' || p_event_id::text, 0)
  );

  select * into v_event
  from public.the_room_events
  where id = p_event_id
  for update;
  if not found then raise exception 'The Room event was not found'; end if;

  select count(distinct row_data.attendee_id), max(row_data.round_number), max(row_data.table_number)
    into v_participant_count, v_round_count, v_table_count
  from jsonb_to_recordset(p_rows) as row_data(
    attendee_id uuid,
    round_number integer,
    table_number integer,
    seat_number integer
  );

  if v_round_count <> v_event.round_count or v_table_count > v_event.table_count then
    raise exception 'Schedule dimensions do not match The Room event configuration';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as row_data(
      attendee_id uuid,
      round_number integer,
      table_number integer,
      seat_number integer
    )
    left join public.the_room_attendees attendee
      on attendee.id = row_data.attendee_id and attendee.event_id = p_event_id
    where attendee.id is null
       or attendee.included_in_schedule is not true
       or attendee.attendance_status not in ('registered', 'confirmed')
  ) then
    raise exception 'Schedule contains an attendee outside this The Room event';
  end if;

  update public.the_room_schedule_runs
  set is_active = false
  where event_id = p_event_id and is_active;

  insert into public.the_room_schedule_runs (
    id, event_id, seed, algorithm_version, participant_count,
    table_count, round_count, metrics, is_active
  ) values (
    v_run_id,
    p_event_id,
    p_seed,
    p_algorithm_version,
    v_participant_count,
    v_event.table_count,
    v_event.round_count,
    coalesce(p_metrics, '{}'::jsonb),
    true
  );

  insert into public.the_room_seats (
    schedule_run_id, event_id, round_number, table_number, seat_number, attendee_id
  )
  select
    v_run_id,
    p_event_id,
    row_data.round_number,
    row_data.table_number,
    row_data.seat_number,
    row_data.attendee_id
  from jsonb_to_recordset(p_rows) as row_data(
    attendee_id uuid,
    round_number integer,
    table_number integer,
    seat_number integer
  );

  get diagnostics v_inserted = row_count;
  if v_inserted <> v_participant_count * v_event.round_count then
    raise exception 'Every included attendee must be seated exactly once per round';
  end if;

  update public.the_room_events
  set status = case when status in ('draft', 'registration') then 'ready' else status end,
      updated_at = pg_catalog.now()
  where id = p_event_id;

  return v_run_id;
end;
$$;

revoke execute on function public.replace_the_room_schedule(uuid, text, text, jsonb, jsonb)
  from public, anon, authenticated;
grant execute on function public.replace_the_room_schedule(uuid, text, text, jsonb, jsonb)
  to service_role;
