-- Optional absolute experience feedback for each tablemate after every
-- Event3 group-ranking round. This is separate from preference rankings and
-- never feeds the live matching algorithm.
CREATE TABLE IF NOT EXISTS public.event3_group_member_feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id uuid NOT NULL,
  event_id integer NOT NULL,
  group_round smallint NOT NULL,
  reviewer_number integer NOT NULL,
  member_number integer NOT NULL,
  experience text NOT NULL,
  tags text[] NOT NULL DEFAULT '{}'::text[],
  organizer_note text,
  is_test_mode boolean NOT NULL DEFAULT false,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT event3_group_member_feedback_unique
    UNIQUE (match_id, event_id, group_round, reviewer_number, member_number, is_test_mode),
  CONSTRAINT event3_group_member_feedback_round
    CHECK (group_round IN (1, 2)),
  CONSTRAINT event3_group_member_feedback_no_self
    CHECK (reviewer_number <> member_number),
  CONSTRAINT event3_group_member_feedback_experience
    CHECK (experience IN ('great', 'good', 'neutral', 'uncomfortable')),
  CONSTRAINT event3_group_member_feedback_tags
    CHECK (
      cardinality(tags) BETWEEN 0 AND 3
      AND tags <@ ARRAY[
        'fun', 'comfortable', 'good_listener', 'respectful', 'engaging',
        'quiet', 'hard_to_connect', 'interrupts', 'dominates', 'disrespectful'
      ]::text[]
    ),
  CONSTRAINT event3_group_member_feedback_note_length
    CHECK (organizer_note IS NULL OR char_length(organizer_note) <= 300)
);

CREATE INDEX IF NOT EXISTS idx_event3_group_member_feedback_review
  ON public.event3_group_member_feedback
  (match_id, event_id, is_test_mode, group_round, reviewer_number);

CREATE INDEX IF NOT EXISTS idx_event3_group_member_feedback_member
  ON public.event3_group_member_feedback
  (match_id, event_id, is_test_mode, member_number);

COMMENT ON TABLE public.event3_group_member_feedback IS
  'Optional per-tablemate group experience feedback; service-only and excluded from live matching.';

ALTER TABLE public.event3_group_member_feedback ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.event3_group_member_feedback FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.event3_group_member_feedback_id_seq FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.event3_group_member_feedback TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.event3_group_member_feedback_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.replace_event3_group_member_feedback(
  p_match_id uuid,
  p_event_id integer,
  p_group_round smallint,
  p_reviewer_number integer,
  p_is_test_mode boolean,
  p_rows jsonb
)
RETURNS integer
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_count integer := 0;
BEGIN
  IF p_group_round NOT IN (1, 2) THEN
    RAISE EXCEPTION 'Group round must be 1 or 2';
  END IF;
  IF pg_catalog.jsonb_typeof(COALESCE(p_rows, '[]'::jsonb)) <> 'array' THEN
    RAISE EXCEPTION 'Feedback rows must be an array';
  END IF;

  DELETE FROM public.event3_group_member_feedback
  WHERE match_id = p_match_id
    AND event_id = p_event_id
    AND group_round = p_group_round
    AND reviewer_number = p_reviewer_number
    AND is_test_mode = p_is_test_mode;

  INSERT INTO public.event3_group_member_feedback (
    match_id, event_id, group_round, reviewer_number, member_number,
    experience, tags, organizer_note, is_test_mode, updated_at
  )
  SELECT
    p_match_id,
    p_event_id,
    p_group_round,
    p_reviewer_number,
    row_data.member_number,
    row_data.experience,
    COALESCE(row_data.tags, '{}'::text[]),
    NULLIF(pg_catalog.btrim(row_data.organizer_note), ''),
    p_is_test_mode,
    pg_catalog.now()
  FROM pg_catalog.jsonb_to_recordset(COALESCE(p_rows, '[]'::jsonb)) AS row_data(
    member_number integer,
    experience text,
    tags text[],
    organizer_note text
  );

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.replace_event3_group_member_feedback(uuid, integer, smallint, integer, boolean, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.replace_event3_group_member_feedback(uuid, integer, smallint, integer, boolean, jsonb)
  TO service_role;
